#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVProcessor.Database.Tables
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BackendAdmin")]
	public partial class BackEndAdminDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Company(tbl_Company instance);
    partial void Updatetbl_Company(tbl_Company instance);
    partial void Deletetbl_Company(tbl_Company instance);
    partial void Inserttbl_Server_FTP_Account(tbl_Server_FTP_Account instance);
    partial void Updatetbl_Server_FTP_Account(tbl_Server_FTP_Account instance);
    partial void Deletetbl_Server_FTP_Account(tbl_Server_FTP_Account instance);
    partial void Inserttbl_Site_Enterprise(tbl_Site_Enterprise instance);
    partial void Updatetbl_Site_Enterprise(tbl_Site_Enterprise instance);
    partial void Deletetbl_Site_Enterprise(tbl_Site_Enterprise instance);
    partial void Inserttbl_Site_XSI_Detail(tbl_Site_XSI_Detail instance);
    partial void Updatetbl_Site_XSI_Detail(tbl_Site_XSI_Detail instance);
    partial void Deletetbl_Site_XSI_Detail(tbl_Site_XSI_Detail instance);
    partial void Inserttbl_User(tbl_User instance);
    partial void Updatetbl_User(tbl_User instance);
    partial void Deletetbl_User(tbl_User instance);
    partial void Inserttbl_User_Credential(tbl_User_Credential instance);
    partial void Updatetbl_User_Credential(tbl_User_Credential instance);
    partial void Deletetbl_User_Credential(tbl_User_Credential instance);
    partial void Inserttbl_Site(tbl_Site instance);
    partial void Updatetbl_Site(tbl_Site instance);
    partial void Deletetbl_Site(tbl_Site instance);
    partial void Inserttbl_Site_UnitType(tbl_Site_UnitType instance);
    partial void Updatetbl_Site_UnitType(tbl_Site_UnitType instance);
    partial void Deletetbl_Site_UnitType(tbl_Site_UnitType instance);
    partial void Inserttbl_UnitType(tbl_UnitType instance);
    partial void Updatetbl_UnitType(tbl_UnitType instance);
    partial void Deletetbl_UnitType(tbl_UnitType instance);
    partial void Inserttbl_Job_PND(tbl_Job_PND instance);
    partial void Updatetbl_Job_PND(tbl_Job_PND instance);
    partial void Deletetbl_Job_PND(tbl_Job_PND instance);
    partial void Inserttbl_Site_Community(tbl_Site_Community instance);
    partial void Updatetbl_Site_Community(tbl_Site_Community instance);
    partial void Deletetbl_Site_Community(tbl_Site_Community instance);
    #endregion
		
		public BackEndAdminDataContext() : 
				base(global::CSVProcessor.Database.Properties.Settings.Default.BackendAdminConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BackEndAdminDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BackEndAdminDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BackEndAdminDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BackEndAdminDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Company> tbl_Companies
		{
			get
			{
				return this.GetTable<tbl_Company>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Server_FTP_Account> tbl_Server_FTP_Accounts
		{
			get
			{
				return this.GetTable<tbl_Server_FTP_Account>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Site_Enterprise> tbl_Site_Enterprises
		{
			get
			{
				return this.GetTable<tbl_Site_Enterprise>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Site_XSI_Detail> tbl_Site_XSI_Details
		{
			get
			{
				return this.GetTable<tbl_Site_XSI_Detail>();
			}
		}
		
		public System.Data.Linq.Table<tbl_User> tbl_Users
		{
			get
			{
				return this.GetTable<tbl_User>();
			}
		}
		
		public System.Data.Linq.Table<tbl_User_Credential> tbl_User_Credentials
		{
			get
			{
				return this.GetTable<tbl_User_Credential>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Site> tbl_Sites
		{
			get
			{
				return this.GetTable<tbl_Site>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Site_UnitType> tbl_Site_UnitTypes
		{
			get
			{
				return this.GetTable<tbl_Site_UnitType>();
			}
		}
		
		public System.Data.Linq.Table<tbl_UnitType> tbl_UnitTypes
		{
			get
			{
				return this.GetTable<tbl_UnitType>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Job_PND> tbl_Job_PNDs
		{
			get
			{
				return this.GetTable<tbl_Job_PND>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Site_Community> tbl_Site_Communities
		{
			get
			{
				return this.GetTable<tbl_Site_Community>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Company")]
	public partial class tbl_Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tbl_CompanyId;
		
		private string _Company_Name;
		
		private int _tbl_AddressId;
		
		private string _Company_Logo;
		
		private string _Company_Siteaccess;
		
		private System.Nullable<int> _Parent_CompanyId;
		
		private bool _Company_Active;
		
		private System.Nullable<int> _tbl_Collection_ProcessId;
		
		private System.Nullable<int> _tbl_Server_FTP_TypeId;
		
		private EntitySet<tbl_Company> _tbl_Companies;
		
		private EntitySet<tbl_Site> _tbl_Sites;
		
		private EntityRef<tbl_Company> _tbl_Company1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontbl_CompanyIdChanging(int value);
    partial void Ontbl_CompanyIdChanged();
    partial void OnCompany_NameChanging(string value);
    partial void OnCompany_NameChanged();
    partial void Ontbl_AddressIdChanging(int value);
    partial void Ontbl_AddressIdChanged();
    partial void OnCompany_LogoChanging(string value);
    partial void OnCompany_LogoChanged();
    partial void OnCompany_SiteaccessChanging(string value);
    partial void OnCompany_SiteaccessChanged();
    partial void OnParent_CompanyIdChanging(System.Nullable<int> value);
    partial void OnParent_CompanyIdChanged();
    partial void OnCompany_ActiveChanging(bool value);
    partial void OnCompany_ActiveChanged();
    partial void Ontbl_Collection_ProcessIdChanging(System.Nullable<int> value);
    partial void Ontbl_Collection_ProcessIdChanged();
    partial void Ontbl_Server_FTP_TypeIdChanging(System.Nullable<int> value);
    partial void Ontbl_Server_FTP_TypeIdChanged();
    #endregion
		
		public tbl_Company()
		{
			this._tbl_Companies = new EntitySet<tbl_Company>(new Action<tbl_Company>(this.attach_tbl_Companies), new Action<tbl_Company>(this.detach_tbl_Companies));
			this._tbl_Sites = new EntitySet<tbl_Site>(new Action<tbl_Site>(this.attach_tbl_Sites), new Action<tbl_Site>(this.detach_tbl_Sites));
			this._tbl_Company1 = default(EntityRef<tbl_Company>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_CompanyId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tbl_CompanyId
		{
			get
			{
				return this._tbl_CompanyId;
			}
			set
			{
				if ((this._tbl_CompanyId != value))
				{
					this.Ontbl_CompanyIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_CompanyId = value;
					this.SendPropertyChanged("tbl_CompanyId");
					this.Ontbl_CompanyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Company_Name
		{
			get
			{
				return this._Company_Name;
			}
			set
			{
				if ((this._Company_Name != value))
				{
					this.OnCompany_NameChanging(value);
					this.SendPropertyChanging();
					this._Company_Name = value;
					this.SendPropertyChanged("Company_Name");
					this.OnCompany_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_AddressId", DbType="Int NOT NULL")]
		public int tbl_AddressId
		{
			get
			{
				return this._tbl_AddressId;
			}
			set
			{
				if ((this._tbl_AddressId != value))
				{
					this.Ontbl_AddressIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_AddressId = value;
					this.SendPropertyChanged("tbl_AddressId");
					this.Ontbl_AddressIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Logo", DbType="VarChar(50)")]
		public string Company_Logo
		{
			get
			{
				return this._Company_Logo;
			}
			set
			{
				if ((this._Company_Logo != value))
				{
					this.OnCompany_LogoChanging(value);
					this.SendPropertyChanging();
					this._Company_Logo = value;
					this.SendPropertyChanged("Company_Logo");
					this.OnCompany_LogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Siteaccess", DbType="VarChar(3)")]
		public string Company_Siteaccess
		{
			get
			{
				return this._Company_Siteaccess;
			}
			set
			{
				if ((this._Company_Siteaccess != value))
				{
					this.OnCompany_SiteaccessChanging(value);
					this.SendPropertyChanging();
					this._Company_Siteaccess = value;
					this.SendPropertyChanged("Company_Siteaccess");
					this.OnCompany_SiteaccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_CompanyId", DbType="Int")]
		public System.Nullable<int> Parent_CompanyId
		{
			get
			{
				return this._Parent_CompanyId;
			}
			set
			{
				if ((this._Parent_CompanyId != value))
				{
					if (this._tbl_Company1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParent_CompanyIdChanging(value);
					this.SendPropertyChanging();
					this._Parent_CompanyId = value;
					this.SendPropertyChanged("Parent_CompanyId");
					this.OnParent_CompanyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Active", DbType="Bit NOT NULL")]
		public bool Company_Active
		{
			get
			{
				return this._Company_Active;
			}
			set
			{
				if ((this._Company_Active != value))
				{
					this.OnCompany_ActiveChanging(value);
					this.SendPropertyChanging();
					this._Company_Active = value;
					this.SendPropertyChanged("Company_Active");
					this.OnCompany_ActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Collection_ProcessId", DbType="Int")]
		public System.Nullable<int> tbl_Collection_ProcessId
		{
			get
			{
				return this._tbl_Collection_ProcessId;
			}
			set
			{
				if ((this._tbl_Collection_ProcessId != value))
				{
					this.Ontbl_Collection_ProcessIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Collection_ProcessId = value;
					this.SendPropertyChanged("tbl_Collection_ProcessId");
					this.Ontbl_Collection_ProcessIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Server_FTP_TypeId", DbType="Int")]
		public System.Nullable<int> tbl_Server_FTP_TypeId
		{
			get
			{
				return this._tbl_Server_FTP_TypeId;
			}
			set
			{
				if ((this._tbl_Server_FTP_TypeId != value))
				{
					this.Ontbl_Server_FTP_TypeIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Server_FTP_TypeId = value;
					this.SendPropertyChanged("tbl_Server_FTP_TypeId");
					this.Ontbl_Server_FTP_TypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Company_tbl_Company", Storage="_tbl_Companies", ThisKey="tbl_CompanyId", OtherKey="Parent_CompanyId")]
		public EntitySet<tbl_Company> tbl_Companies
		{
			get
			{
				return this._tbl_Companies;
			}
			set
			{
				this._tbl_Companies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Company_tbl_Site", Storage="_tbl_Sites", ThisKey="tbl_CompanyId", OtherKey="tbl_companyId")]
		public EntitySet<tbl_Site> tbl_Sites
		{
			get
			{
				return this._tbl_Sites;
			}
			set
			{
				this._tbl_Sites.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Company_tbl_Company", Storage="_tbl_Company1", ThisKey="Parent_CompanyId", OtherKey="tbl_CompanyId", IsForeignKey=true)]
		public tbl_Company tbl_Company1
		{
			get
			{
				return this._tbl_Company1.Entity;
			}
			set
			{
				tbl_Company previousValue = this._tbl_Company1.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Company1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Company1.Entity = null;
						previousValue.tbl_Companies.Remove(this);
					}
					this._tbl_Company1.Entity = value;
					if ((value != null))
					{
						value.tbl_Companies.Add(this);
						this._Parent_CompanyId = value.tbl_CompanyId;
					}
					else
					{
						this._Parent_CompanyId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Company1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Companies(tbl_Company entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Company1 = this;
		}
		
		private void detach_tbl_Companies(tbl_Company entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Company1 = null;
		}
		
		private void attach_tbl_Sites(tbl_Site entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Company = this;
		}
		
		private void detach_tbl_Sites(tbl_Site entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Company = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Server_FTP_Account")]
	public partial class tbl_Server_FTP_Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tbl_Server_FTP_AccountId;
		
		private int _tbl_ServerId;
		
		private string _Server_FTP_Account_Name;
		
		private string _Server_FTP_Account_Password;
		
		private EntitySet<tbl_Site> _tbl_Sites;
		
		private EntitySet<tbl_Site> _tbl_Sites1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontbl_Server_FTP_AccountIdChanging(int value);
    partial void Ontbl_Server_FTP_AccountIdChanged();
    partial void Ontbl_ServerIdChanging(int value);
    partial void Ontbl_ServerIdChanged();
    partial void OnServer_FTP_Account_NameChanging(string value);
    partial void OnServer_FTP_Account_NameChanged();
    partial void OnServer_FTP_Account_PasswordChanging(string value);
    partial void OnServer_FTP_Account_PasswordChanged();
    #endregion
		
		public tbl_Server_FTP_Account()
		{
			this._tbl_Sites = new EntitySet<tbl_Site>(new Action<tbl_Site>(this.attach_tbl_Sites), new Action<tbl_Site>(this.detach_tbl_Sites));
			this._tbl_Sites1 = new EntitySet<tbl_Site>(new Action<tbl_Site>(this.attach_tbl_Sites1), new Action<tbl_Site>(this.detach_tbl_Sites1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Server_FTP_AccountId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tbl_Server_FTP_AccountId
		{
			get
			{
				return this._tbl_Server_FTP_AccountId;
			}
			set
			{
				if ((this._tbl_Server_FTP_AccountId != value))
				{
					this.Ontbl_Server_FTP_AccountIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Server_FTP_AccountId = value;
					this.SendPropertyChanged("tbl_Server_FTP_AccountId");
					this.Ontbl_Server_FTP_AccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_ServerId", DbType="Int NOT NULL")]
		public int tbl_ServerId
		{
			get
			{
				return this._tbl_ServerId;
			}
			set
			{
				if ((this._tbl_ServerId != value))
				{
					this.Ontbl_ServerIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_ServerId = value;
					this.SendPropertyChanged("tbl_ServerId");
					this.Ontbl_ServerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Server_FTP_Account_Name", DbType="VarChar(50)")]
		public string Server_FTP_Account_Name
		{
			get
			{
				return this._Server_FTP_Account_Name;
			}
			set
			{
				if ((this._Server_FTP_Account_Name != value))
				{
					this.OnServer_FTP_Account_NameChanging(value);
					this.SendPropertyChanging();
					this._Server_FTP_Account_Name = value;
					this.SendPropertyChanged("Server_FTP_Account_Name");
					this.OnServer_FTP_Account_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Server_FTP_Account_Password", DbType="VarChar(50)")]
		public string Server_FTP_Account_Password
		{
			get
			{
				return this._Server_FTP_Account_Password;
			}
			set
			{
				if ((this._Server_FTP_Account_Password != value))
				{
					this.OnServer_FTP_Account_PasswordChanging(value);
					this.SendPropertyChanging();
					this._Server_FTP_Account_Password = value;
					this.SendPropertyChanged("Server_FTP_Account_Password");
					this.OnServer_FTP_Account_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Server_FTP_Account_tbl_Site", Storage="_tbl_Sites", ThisKey="tbl_Server_FTP_AccountId", OtherKey="tbl_Server_FTP_AccountId_Local")]
		public EntitySet<tbl_Site> tbl_Sites
		{
			get
			{
				return this._tbl_Sites;
			}
			set
			{
				this._tbl_Sites.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Server_FTP_Account_tbl_Site1", Storage="_tbl_Sites1", ThisKey="tbl_Server_FTP_AccountId", OtherKey="tbl_Server_FTP_AccountId_Remote")]
		public EntitySet<tbl_Site> tbl_Sites1
		{
			get
			{
				return this._tbl_Sites1;
			}
			set
			{
				this._tbl_Sites1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Sites(tbl_Site entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Server_FTP_Account = this;
		}
		
		private void detach_tbl_Sites(tbl_Site entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Server_FTP_Account = null;
		}
		
		private void attach_tbl_Sites1(tbl_Site entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Server_FTP_Account1 = this;
		}
		
		private void detach_tbl_Sites1(tbl_Site entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Server_FTP_Account1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Site_Enterprise")]
	public partial class tbl_Site_Enterprise : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tbl_Site_EnterpriseId;
		
		private int _tbl_SiteId;
		
		private string _tbl_Site_Enterprise_Name;
		
		private bool _tbl_Site_Enterprise_Active;
		
		private EntityRef<tbl_Site> _tbl_Site;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontbl_Site_EnterpriseIdChanging(int value);
    partial void Ontbl_Site_EnterpriseIdChanged();
    partial void Ontbl_SiteIdChanging(int value);
    partial void Ontbl_SiteIdChanged();
    partial void Ontbl_Site_Enterprise_NameChanging(string value);
    partial void Ontbl_Site_Enterprise_NameChanged();
    partial void Ontbl_Site_Enterprise_ActiveChanging(bool value);
    partial void Ontbl_Site_Enterprise_ActiveChanged();
    #endregion
		
		public tbl_Site_Enterprise()
		{
			this._tbl_Site = default(EntityRef<tbl_Site>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_EnterpriseId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tbl_Site_EnterpriseId
		{
			get
			{
				return this._tbl_Site_EnterpriseId;
			}
			set
			{
				if ((this._tbl_Site_EnterpriseId != value))
				{
					this.Ontbl_Site_EnterpriseIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_EnterpriseId = value;
					this.SendPropertyChanged("tbl_Site_EnterpriseId");
					this.Ontbl_Site_EnterpriseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_SiteId", DbType="Int NOT NULL")]
		public int tbl_SiteId
		{
			get
			{
				return this._tbl_SiteId;
			}
			set
			{
				if ((this._tbl_SiteId != value))
				{
					if (this._tbl_Site.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontbl_SiteIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_SiteId = value;
					this.SendPropertyChanged("tbl_SiteId");
					this.Ontbl_SiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_Enterprise_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string tbl_Site_Enterprise_Name
		{
			get
			{
				return this._tbl_Site_Enterprise_Name;
			}
			set
			{
				if ((this._tbl_Site_Enterprise_Name != value))
				{
					this.Ontbl_Site_Enterprise_NameChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_Enterprise_Name = value;
					this.SendPropertyChanged("tbl_Site_Enterprise_Name");
					this.Ontbl_Site_Enterprise_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_Enterprise_Active", DbType="Bit NOT NULL")]
		public bool tbl_Site_Enterprise_Active
		{
			get
			{
				return this._tbl_Site_Enterprise_Active;
			}
			set
			{
				if ((this._tbl_Site_Enterprise_Active != value))
				{
					this.Ontbl_Site_Enterprise_ActiveChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_Enterprise_Active = value;
					this.SendPropertyChanged("tbl_Site_Enterprise_Active");
					this.Ontbl_Site_Enterprise_ActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Site_tbl_Site_Enterprise", Storage="_tbl_Site", ThisKey="tbl_SiteId", OtherKey="tbl_SiteId", IsForeignKey=true)]
		public tbl_Site tbl_Site
		{
			get
			{
				return this._tbl_Site.Entity;
			}
			set
			{
				tbl_Site previousValue = this._tbl_Site.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Site.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Site.Entity = null;
						previousValue.tbl_Site_Enterprises.Remove(this);
					}
					this._tbl_Site.Entity = value;
					if ((value != null))
					{
						value.tbl_Site_Enterprises.Add(this);
						this._tbl_SiteId = value.tbl_SiteId;
					}
					else
					{
						this._tbl_SiteId = default(int);
					}
					this.SendPropertyChanged("tbl_Site");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Site_XSI_Details")]
	public partial class tbl_Site_XSI_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tbl_Site_XSI_DetailsId;
		
		private int _tbl_Company_XSI_MasterDetailsId;
		
		private int _tbl_SiteId;
		
		private string _tbl_Site_XSI_Username;
		
		private string _tbl_Site_XSI_Password;
		
		private System.Nullable<bool> _tbl_Site_XSI_Active;
		
		private EntityRef<tbl_Site> _tbl_Site;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontbl_Site_XSI_DetailsIdChanging(int value);
    partial void Ontbl_Site_XSI_DetailsIdChanged();
    partial void Ontbl_Company_XSI_MasterDetailsIdChanging(int value);
    partial void Ontbl_Company_XSI_MasterDetailsIdChanged();
    partial void Ontbl_SiteIdChanging(int value);
    partial void Ontbl_SiteIdChanged();
    partial void Ontbl_Site_XSI_UsernameChanging(string value);
    partial void Ontbl_Site_XSI_UsernameChanged();
    partial void Ontbl_Site_XSI_PasswordChanging(string value);
    partial void Ontbl_Site_XSI_PasswordChanged();
    partial void Ontbl_Site_XSI_ActiveChanging(System.Nullable<bool> value);
    partial void Ontbl_Site_XSI_ActiveChanged();
    #endregion
		
		public tbl_Site_XSI_Detail()
		{
			this._tbl_Site = default(EntityRef<tbl_Site>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_XSI_DetailsId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tbl_Site_XSI_DetailsId
		{
			get
			{
				return this._tbl_Site_XSI_DetailsId;
			}
			set
			{
				if ((this._tbl_Site_XSI_DetailsId != value))
				{
					this.Ontbl_Site_XSI_DetailsIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_XSI_DetailsId = value;
					this.SendPropertyChanged("tbl_Site_XSI_DetailsId");
					this.Ontbl_Site_XSI_DetailsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Company_XSI_MasterDetailsId", DbType="Int NOT NULL")]
		public int tbl_Company_XSI_MasterDetailsId
		{
			get
			{
				return this._tbl_Company_XSI_MasterDetailsId;
			}
			set
			{
				if ((this._tbl_Company_XSI_MasterDetailsId != value))
				{
					this.Ontbl_Company_XSI_MasterDetailsIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Company_XSI_MasterDetailsId = value;
					this.SendPropertyChanged("tbl_Company_XSI_MasterDetailsId");
					this.Ontbl_Company_XSI_MasterDetailsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_SiteId", DbType="Int NOT NULL")]
		public int tbl_SiteId
		{
			get
			{
				return this._tbl_SiteId;
			}
			set
			{
				if ((this._tbl_SiteId != value))
				{
					if (this._tbl_Site.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontbl_SiteIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_SiteId = value;
					this.SendPropertyChanged("tbl_SiteId");
					this.Ontbl_SiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_XSI_Username", DbType="VarChar(300)")]
		public string tbl_Site_XSI_Username
		{
			get
			{
				return this._tbl_Site_XSI_Username;
			}
			set
			{
				if ((this._tbl_Site_XSI_Username != value))
				{
					this.Ontbl_Site_XSI_UsernameChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_XSI_Username = value;
					this.SendPropertyChanged("tbl_Site_XSI_Username");
					this.Ontbl_Site_XSI_UsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_XSI_Password", DbType="VarChar(200)")]
		public string tbl_Site_XSI_Password
		{
			get
			{
				return this._tbl_Site_XSI_Password;
			}
			set
			{
				if ((this._tbl_Site_XSI_Password != value))
				{
					this.Ontbl_Site_XSI_PasswordChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_XSI_Password = value;
					this.SendPropertyChanged("tbl_Site_XSI_Password");
					this.Ontbl_Site_XSI_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_XSI_Active", DbType="Bit")]
		public System.Nullable<bool> tbl_Site_XSI_Active
		{
			get
			{
				return this._tbl_Site_XSI_Active;
			}
			set
			{
				if ((this._tbl_Site_XSI_Active != value))
				{
					this.Ontbl_Site_XSI_ActiveChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_XSI_Active = value;
					this.SendPropertyChanged("tbl_Site_XSI_Active");
					this.Ontbl_Site_XSI_ActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Site_tbl_Site_XSI_Detail", Storage="_tbl_Site", ThisKey="tbl_SiteId", OtherKey="tbl_SiteId", IsForeignKey=true)]
		public tbl_Site tbl_Site
		{
			get
			{
				return this._tbl_Site.Entity;
			}
			set
			{
				tbl_Site previousValue = this._tbl_Site.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Site.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Site.Entity = null;
						previousValue.tbl_Site_XSI_Details.Remove(this);
					}
					this._tbl_Site.Entity = value;
					if ((value != null))
					{
						value.tbl_Site_XSI_Details.Add(this);
						this._tbl_SiteId = value.tbl_SiteId;
					}
					else
					{
						this._tbl_SiteId = default(int);
					}
					this.SendPropertyChanged("tbl_Site");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_User")]
	public partial class tbl_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tbl_UserId;
		
		private System.Nullable<int> _tbl_User_CredentialsId;
		
		private System.Nullable<int> _tbl_User_PermissionsId;
		
		private string _User_Title;
		
		private string _User_Forename;
		
		private string _User_Surname;
		
		private System.Nullable<bool> _User_Active;
		
		private System.Nullable<bool> _User_FirstTimeLogin;
		
		private System.Nullable<System.DateTime> _User_CreatedDatetime;
		
		private System.Nullable<int> _User_CreatedBy_UserId;
		
		private EntitySet<tbl_User> _tbl_Users;
		
		private EntityRef<tbl_User> _tbl_User1;
		
		private EntityRef<tbl_User_Credential> _tbl_User_Credential;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontbl_UserIdChanging(int value);
    partial void Ontbl_UserIdChanged();
    partial void Ontbl_User_CredentialsIdChanging(System.Nullable<int> value);
    partial void Ontbl_User_CredentialsIdChanged();
    partial void Ontbl_User_PermissionsIdChanging(System.Nullable<int> value);
    partial void Ontbl_User_PermissionsIdChanged();
    partial void OnUser_TitleChanging(string value);
    partial void OnUser_TitleChanged();
    partial void OnUser_ForenameChanging(string value);
    partial void OnUser_ForenameChanged();
    partial void OnUser_SurnameChanging(string value);
    partial void OnUser_SurnameChanged();
    partial void OnUser_ActiveChanging(System.Nullable<bool> value);
    partial void OnUser_ActiveChanged();
    partial void OnUser_FirstTimeLoginChanging(System.Nullable<bool> value);
    partial void OnUser_FirstTimeLoginChanged();
    partial void OnUser_CreatedDatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUser_CreatedDatetimeChanged();
    partial void OnUser_CreatedBy_UserIdChanging(System.Nullable<int> value);
    partial void OnUser_CreatedBy_UserIdChanged();
    #endregion
		
		public tbl_User()
		{
			this._tbl_Users = new EntitySet<tbl_User>(new Action<tbl_User>(this.attach_tbl_Users), new Action<tbl_User>(this.detach_tbl_Users));
			this._tbl_User1 = default(EntityRef<tbl_User>);
			this._tbl_User_Credential = default(EntityRef<tbl_User_Credential>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_UserId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tbl_UserId
		{
			get
			{
				return this._tbl_UserId;
			}
			set
			{
				if ((this._tbl_UserId != value))
				{
					this.Ontbl_UserIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_UserId = value;
					this.SendPropertyChanged("tbl_UserId");
					this.Ontbl_UserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_User_CredentialsId", DbType="Int")]
		public System.Nullable<int> tbl_User_CredentialsId
		{
			get
			{
				return this._tbl_User_CredentialsId;
			}
			set
			{
				if ((this._tbl_User_CredentialsId != value))
				{
					if (this._tbl_User_Credential.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontbl_User_CredentialsIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_User_CredentialsId = value;
					this.SendPropertyChanged("tbl_User_CredentialsId");
					this.Ontbl_User_CredentialsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_User_PermissionsId", DbType="Int")]
		public System.Nullable<int> tbl_User_PermissionsId
		{
			get
			{
				return this._tbl_User_PermissionsId;
			}
			set
			{
				if ((this._tbl_User_PermissionsId != value))
				{
					this.Ontbl_User_PermissionsIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_User_PermissionsId = value;
					this.SendPropertyChanged("tbl_User_PermissionsId");
					this.Ontbl_User_PermissionsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Title", DbType="VarChar(4)")]
		public string User_Title
		{
			get
			{
				return this._User_Title;
			}
			set
			{
				if ((this._User_Title != value))
				{
					this.OnUser_TitleChanging(value);
					this.SendPropertyChanging();
					this._User_Title = value;
					this.SendPropertyChanged("User_Title");
					this.OnUser_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Forename", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string User_Forename
		{
			get
			{
				return this._User_Forename;
			}
			set
			{
				if ((this._User_Forename != value))
				{
					this.OnUser_ForenameChanging(value);
					this.SendPropertyChanging();
					this._User_Forename = value;
					this.SendPropertyChanged("User_Forename");
					this.OnUser_ForenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Surname", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string User_Surname
		{
			get
			{
				return this._User_Surname;
			}
			set
			{
				if ((this._User_Surname != value))
				{
					this.OnUser_SurnameChanging(value);
					this.SendPropertyChanging();
					this._User_Surname = value;
					this.SendPropertyChanged("User_Surname");
					this.OnUser_SurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Active", DbType="Bit")]
		public System.Nullable<bool> User_Active
		{
			get
			{
				return this._User_Active;
			}
			set
			{
				if ((this._User_Active != value))
				{
					this.OnUser_ActiveChanging(value);
					this.SendPropertyChanging();
					this._User_Active = value;
					this.SendPropertyChanged("User_Active");
					this.OnUser_ActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_FirstTimeLogin", DbType="Bit")]
		public System.Nullable<bool> User_FirstTimeLogin
		{
			get
			{
				return this._User_FirstTimeLogin;
			}
			set
			{
				if ((this._User_FirstTimeLogin != value))
				{
					this.OnUser_FirstTimeLoginChanging(value);
					this.SendPropertyChanging();
					this._User_FirstTimeLogin = value;
					this.SendPropertyChanged("User_FirstTimeLogin");
					this.OnUser_FirstTimeLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_CreatedDatetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> User_CreatedDatetime
		{
			get
			{
				return this._User_CreatedDatetime;
			}
			set
			{
				if ((this._User_CreatedDatetime != value))
				{
					this.OnUser_CreatedDatetimeChanging(value);
					this.SendPropertyChanging();
					this._User_CreatedDatetime = value;
					this.SendPropertyChanged("User_CreatedDatetime");
					this.OnUser_CreatedDatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_CreatedBy_UserId", DbType="Int")]
		public System.Nullable<int> User_CreatedBy_UserId
		{
			get
			{
				return this._User_CreatedBy_UserId;
			}
			set
			{
				if ((this._User_CreatedBy_UserId != value))
				{
					if (this._tbl_User1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_CreatedBy_UserIdChanging(value);
					this.SendPropertyChanging();
					this._User_CreatedBy_UserId = value;
					this.SendPropertyChanged("User_CreatedBy_UserId");
					this.OnUser_CreatedBy_UserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_User_tbl_User", Storage="_tbl_Users", ThisKey="tbl_UserId", OtherKey="User_CreatedBy_UserId")]
		public EntitySet<tbl_User> tbl_Users
		{
			get
			{
				return this._tbl_Users;
			}
			set
			{
				this._tbl_Users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_User_tbl_User", Storage="_tbl_User1", ThisKey="User_CreatedBy_UserId", OtherKey="tbl_UserId", IsForeignKey=true)]
		public tbl_User tbl_User1
		{
			get
			{
				return this._tbl_User1.Entity;
			}
			set
			{
				tbl_User previousValue = this._tbl_User1.Entity;
				if (((previousValue != value) 
							|| (this._tbl_User1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_User1.Entity = null;
						previousValue.tbl_Users.Remove(this);
					}
					this._tbl_User1.Entity = value;
					if ((value != null))
					{
						value.tbl_Users.Add(this);
						this._User_CreatedBy_UserId = value.tbl_UserId;
					}
					else
					{
						this._User_CreatedBy_UserId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_User1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_User_Credential_tbl_User", Storage="_tbl_User_Credential", ThisKey="tbl_User_CredentialsId", OtherKey="tbl_User_CredentialsId", IsForeignKey=true)]
		public tbl_User_Credential tbl_User_Credential
		{
			get
			{
				return this._tbl_User_Credential.Entity;
			}
			set
			{
				tbl_User_Credential previousValue = this._tbl_User_Credential.Entity;
				if (((previousValue != value) 
							|| (this._tbl_User_Credential.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_User_Credential.Entity = null;
						previousValue.tbl_Users.Remove(this);
					}
					this._tbl_User_Credential.Entity = value;
					if ((value != null))
					{
						value.tbl_Users.Add(this);
						this._tbl_User_CredentialsId = value.tbl_User_CredentialsId;
					}
					else
					{
						this._tbl_User_CredentialsId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_User_Credential");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Users(tbl_User entity)
		{
			this.SendPropertyChanging();
			entity.tbl_User1 = this;
		}
		
		private void detach_tbl_Users(tbl_User entity)
		{
			this.SendPropertyChanging();
			entity.tbl_User1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_User_Credentials")]
	public partial class tbl_User_Credential : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tbl_User_CredentialsId;
		
		private string _User_Credentials_Username;
		
		private string _User_Credentials_Password;
		
		private string _User_Credentials_EmailAddress;
		
		private string _User_Credentials_SecurityQuestion;
		
		private string _User_Credentials_SecurityAnswer;
		
		private System.Nullable<bool> _User_Credentials_PasswordMustBeChanged;
		
		private System.Nullable<System.DateTime> _User_Credentials_PasswordExpiryDateTime;
		
		private System.Nullable<bool> _User_Credentials_FirstLogin;
		
		private string _User_Credentials_Salt;
		
		private EntitySet<tbl_User> _tbl_Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontbl_User_CredentialsIdChanging(int value);
    partial void Ontbl_User_CredentialsIdChanged();
    partial void OnUser_Credentials_UsernameChanging(string value);
    partial void OnUser_Credentials_UsernameChanged();
    partial void OnUser_Credentials_PasswordChanging(string value);
    partial void OnUser_Credentials_PasswordChanged();
    partial void OnUser_Credentials_EmailAddressChanging(string value);
    partial void OnUser_Credentials_EmailAddressChanged();
    partial void OnUser_Credentials_SecurityQuestionChanging(string value);
    partial void OnUser_Credentials_SecurityQuestionChanged();
    partial void OnUser_Credentials_SecurityAnswerChanging(string value);
    partial void OnUser_Credentials_SecurityAnswerChanged();
    partial void OnUser_Credentials_PasswordMustBeChangedChanging(System.Nullable<bool> value);
    partial void OnUser_Credentials_PasswordMustBeChangedChanged();
    partial void OnUser_Credentials_PasswordExpiryDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUser_Credentials_PasswordExpiryDateTimeChanged();
    partial void OnUser_Credentials_FirstLoginChanging(System.Nullable<bool> value);
    partial void OnUser_Credentials_FirstLoginChanged();
    partial void OnUser_Credentials_SaltChanging(string value);
    partial void OnUser_Credentials_SaltChanged();
    #endregion
		
		public tbl_User_Credential()
		{
			this._tbl_Users = new EntitySet<tbl_User>(new Action<tbl_User>(this.attach_tbl_Users), new Action<tbl_User>(this.detach_tbl_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_User_CredentialsId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tbl_User_CredentialsId
		{
			get
			{
				return this._tbl_User_CredentialsId;
			}
			set
			{
				if ((this._tbl_User_CredentialsId != value))
				{
					this.Ontbl_User_CredentialsIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_User_CredentialsId = value;
					this.SendPropertyChanged("tbl_User_CredentialsId");
					this.Ontbl_User_CredentialsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Credentials_Username", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string User_Credentials_Username
		{
			get
			{
				return this._User_Credentials_Username;
			}
			set
			{
				if ((this._User_Credentials_Username != value))
				{
					this.OnUser_Credentials_UsernameChanging(value);
					this.SendPropertyChanging();
					this._User_Credentials_Username = value;
					this.SendPropertyChanged("User_Credentials_Username");
					this.OnUser_Credentials_UsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Credentials_Password", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string User_Credentials_Password
		{
			get
			{
				return this._User_Credentials_Password;
			}
			set
			{
				if ((this._User_Credentials_Password != value))
				{
					this.OnUser_Credentials_PasswordChanging(value);
					this.SendPropertyChanging();
					this._User_Credentials_Password = value;
					this.SendPropertyChanged("User_Credentials_Password");
					this.OnUser_Credentials_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Credentials_EmailAddress", DbType="VarChar(50)")]
		public string User_Credentials_EmailAddress
		{
			get
			{
				return this._User_Credentials_EmailAddress;
			}
			set
			{
				if ((this._User_Credentials_EmailAddress != value))
				{
					this.OnUser_Credentials_EmailAddressChanging(value);
					this.SendPropertyChanging();
					this._User_Credentials_EmailAddress = value;
					this.SendPropertyChanged("User_Credentials_EmailAddress");
					this.OnUser_Credentials_EmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Credentials_SecurityQuestion", DbType="VarChar(40)")]
		public string User_Credentials_SecurityQuestion
		{
			get
			{
				return this._User_Credentials_SecurityQuestion;
			}
			set
			{
				if ((this._User_Credentials_SecurityQuestion != value))
				{
					this.OnUser_Credentials_SecurityQuestionChanging(value);
					this.SendPropertyChanging();
					this._User_Credentials_SecurityQuestion = value;
					this.SendPropertyChanged("User_Credentials_SecurityQuestion");
					this.OnUser_Credentials_SecurityQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Credentials_SecurityAnswer", DbType="VarChar(20)")]
		public string User_Credentials_SecurityAnswer
		{
			get
			{
				return this._User_Credentials_SecurityAnswer;
			}
			set
			{
				if ((this._User_Credentials_SecurityAnswer != value))
				{
					this.OnUser_Credentials_SecurityAnswerChanging(value);
					this.SendPropertyChanging();
					this._User_Credentials_SecurityAnswer = value;
					this.SendPropertyChanged("User_Credentials_SecurityAnswer");
					this.OnUser_Credentials_SecurityAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Credentials_PasswordMustBeChanged", DbType="Bit")]
		public System.Nullable<bool> User_Credentials_PasswordMustBeChanged
		{
			get
			{
				return this._User_Credentials_PasswordMustBeChanged;
			}
			set
			{
				if ((this._User_Credentials_PasswordMustBeChanged != value))
				{
					this.OnUser_Credentials_PasswordMustBeChangedChanging(value);
					this.SendPropertyChanging();
					this._User_Credentials_PasswordMustBeChanged = value;
					this.SendPropertyChanged("User_Credentials_PasswordMustBeChanged");
					this.OnUser_Credentials_PasswordMustBeChangedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Credentials_PasswordExpiryDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> User_Credentials_PasswordExpiryDateTime
		{
			get
			{
				return this._User_Credentials_PasswordExpiryDateTime;
			}
			set
			{
				if ((this._User_Credentials_PasswordExpiryDateTime != value))
				{
					this.OnUser_Credentials_PasswordExpiryDateTimeChanging(value);
					this.SendPropertyChanging();
					this._User_Credentials_PasswordExpiryDateTime = value;
					this.SendPropertyChanged("User_Credentials_PasswordExpiryDateTime");
					this.OnUser_Credentials_PasswordExpiryDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Credentials_FirstLogin", DbType="Bit")]
		public System.Nullable<bool> User_Credentials_FirstLogin
		{
			get
			{
				return this._User_Credentials_FirstLogin;
			}
			set
			{
				if ((this._User_Credentials_FirstLogin != value))
				{
					this.OnUser_Credentials_FirstLoginChanging(value);
					this.SendPropertyChanging();
					this._User_Credentials_FirstLogin = value;
					this.SendPropertyChanged("User_Credentials_FirstLogin");
					this.OnUser_Credentials_FirstLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Credentials_Salt", DbType="VarChar(35)")]
		public string User_Credentials_Salt
		{
			get
			{
				return this._User_Credentials_Salt;
			}
			set
			{
				if ((this._User_Credentials_Salt != value))
				{
					this.OnUser_Credentials_SaltChanging(value);
					this.SendPropertyChanging();
					this._User_Credentials_Salt = value;
					this.SendPropertyChanged("User_Credentials_Salt");
					this.OnUser_Credentials_SaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_User_Credential_tbl_User", Storage="_tbl_Users", ThisKey="tbl_User_CredentialsId", OtherKey="tbl_User_CredentialsId")]
		public EntitySet<tbl_User> tbl_Users
		{
			get
			{
				return this._tbl_Users;
			}
			set
			{
				this._tbl_Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Users(tbl_User entity)
		{
			this.SendPropertyChanging();
			entity.tbl_User_Credential = this;
		}
		
		private void detach_tbl_Users(tbl_User entity)
		{
			this.SendPropertyChanging();
			entity.tbl_User_Credential = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Site")]
	public partial class tbl_Site : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tbl_SiteId;
		
		private int _tbl_companyId;
		
		private int _tbl_addressId;
		
		private int _tbl_timezonesId;
		
		private string _Site_name;
		
		private bool _Site_active;
		
		private string _Site_MainLineNumber;
		
		private System.Nullable<int> _tbl_Server_DBDetailsId;
		
		private System.Nullable<int> _tbl_Server_FTP_AccountId_Local;
		
		private System.Nullable<int> _tbl_Server_FTP_AccountId_Remote;
		
		private System.Nullable<int> _tbl_Server_ArchiveFilesId;
		
		private System.Nullable<int> _tbl_ContactFrequencyID;
		
		private EntitySet<tbl_Site_Enterprise> _tbl_Site_Enterprises;
		
		private EntitySet<tbl_Site_XSI_Detail> _tbl_Site_XSI_Details;
		
		private EntitySet<tbl_Site_UnitType> _tbl_Site_UnitTypes;
		
		private EntitySet<tbl_Job_PND> _tbl_Job_PNDs;
		
		private EntityRef<tbl_Company> _tbl_Company;
		
		private EntityRef<tbl_Server_FTP_Account> _tbl_Server_FTP_Account;
		
		private EntityRef<tbl_Server_FTP_Account> _tbl_Server_FTP_Account1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontbl_SiteIdChanging(int value);
    partial void Ontbl_SiteIdChanged();
    partial void Ontbl_companyIdChanging(int value);
    partial void Ontbl_companyIdChanged();
    partial void Ontbl_addressIdChanging(int value);
    partial void Ontbl_addressIdChanged();
    partial void Ontbl_timezonesIdChanging(int value);
    partial void Ontbl_timezonesIdChanged();
    partial void OnSite_nameChanging(string value);
    partial void OnSite_nameChanged();
    partial void OnSite_activeChanging(bool value);
    partial void OnSite_activeChanged();
    partial void OnSite_MainLineNumberChanging(string value);
    partial void OnSite_MainLineNumberChanged();
    partial void Ontbl_Server_DBDetailsIdChanging(System.Nullable<int> value);
    partial void Ontbl_Server_DBDetailsIdChanged();
    partial void Ontbl_Server_FTP_AccountId_LocalChanging(System.Nullable<int> value);
    partial void Ontbl_Server_FTP_AccountId_LocalChanged();
    partial void Ontbl_Server_FTP_AccountId_RemoteChanging(System.Nullable<int> value);
    partial void Ontbl_Server_FTP_AccountId_RemoteChanged();
    partial void Ontbl_Server_ArchiveFilesIdChanging(System.Nullable<int> value);
    partial void Ontbl_Server_ArchiveFilesIdChanged();
    partial void Ontbl_ContactFrequencyIDChanging(System.Nullable<int> value);
    partial void Ontbl_ContactFrequencyIDChanged();
    #endregion
		
		public tbl_Site()
		{
			this._tbl_Site_Enterprises = new EntitySet<tbl_Site_Enterprise>(new Action<tbl_Site_Enterprise>(this.attach_tbl_Site_Enterprises), new Action<tbl_Site_Enterprise>(this.detach_tbl_Site_Enterprises));
			this._tbl_Site_XSI_Details = new EntitySet<tbl_Site_XSI_Detail>(new Action<tbl_Site_XSI_Detail>(this.attach_tbl_Site_XSI_Details), new Action<tbl_Site_XSI_Detail>(this.detach_tbl_Site_XSI_Details));
			this._tbl_Site_UnitTypes = new EntitySet<tbl_Site_UnitType>(new Action<tbl_Site_UnitType>(this.attach_tbl_Site_UnitTypes), new Action<tbl_Site_UnitType>(this.detach_tbl_Site_UnitTypes));
			this._tbl_Job_PNDs = new EntitySet<tbl_Job_PND>(new Action<tbl_Job_PND>(this.attach_tbl_Job_PNDs), new Action<tbl_Job_PND>(this.detach_tbl_Job_PNDs));
			this._tbl_Company = default(EntityRef<tbl_Company>);
			this._tbl_Server_FTP_Account = default(EntityRef<tbl_Server_FTP_Account>);
			this._tbl_Server_FTP_Account1 = default(EntityRef<tbl_Server_FTP_Account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_SiteId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tbl_SiteId
		{
			get
			{
				return this._tbl_SiteId;
			}
			set
			{
				if ((this._tbl_SiteId != value))
				{
					this.Ontbl_SiteIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_SiteId = value;
					this.SendPropertyChanged("tbl_SiteId");
					this.Ontbl_SiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_companyId", DbType="Int NOT NULL")]
		public int tbl_companyId
		{
			get
			{
				return this._tbl_companyId;
			}
			set
			{
				if ((this._tbl_companyId != value))
				{
					if (this._tbl_Company.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontbl_companyIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_companyId = value;
					this.SendPropertyChanged("tbl_companyId");
					this.Ontbl_companyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_addressId", DbType="Int NOT NULL")]
		public int tbl_addressId
		{
			get
			{
				return this._tbl_addressId;
			}
			set
			{
				if ((this._tbl_addressId != value))
				{
					this.Ontbl_addressIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_addressId = value;
					this.SendPropertyChanged("tbl_addressId");
					this.Ontbl_addressIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_timezonesId", DbType="Int NOT NULL")]
		public int tbl_timezonesId
		{
			get
			{
				return this._tbl_timezonesId;
			}
			set
			{
				if ((this._tbl_timezonesId != value))
				{
					this.Ontbl_timezonesIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_timezonesId = value;
					this.SendPropertyChanged("tbl_timezonesId");
					this.Ontbl_timezonesIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_name", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Site_name
		{
			get
			{
				return this._Site_name;
			}
			set
			{
				if ((this._Site_name != value))
				{
					this.OnSite_nameChanging(value);
					this.SendPropertyChanging();
					this._Site_name = value;
					this.SendPropertyChanged("Site_name");
					this.OnSite_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_active", DbType="Bit NOT NULL")]
		public bool Site_active
		{
			get
			{
				return this._Site_active;
			}
			set
			{
				if ((this._Site_active != value))
				{
					this.OnSite_activeChanging(value);
					this.SendPropertyChanging();
					this._Site_active = value;
					this.SendPropertyChanged("Site_active");
					this.OnSite_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_MainLineNumber", DbType="VarChar(20)")]
		public string Site_MainLineNumber
		{
			get
			{
				return this._Site_MainLineNumber;
			}
			set
			{
				if ((this._Site_MainLineNumber != value))
				{
					this.OnSite_MainLineNumberChanging(value);
					this.SendPropertyChanging();
					this._Site_MainLineNumber = value;
					this.SendPropertyChanged("Site_MainLineNumber");
					this.OnSite_MainLineNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Server_DBDetailsId", DbType="Int")]
		public System.Nullable<int> tbl_Server_DBDetailsId
		{
			get
			{
				return this._tbl_Server_DBDetailsId;
			}
			set
			{
				if ((this._tbl_Server_DBDetailsId != value))
				{
					this.Ontbl_Server_DBDetailsIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Server_DBDetailsId = value;
					this.SendPropertyChanged("tbl_Server_DBDetailsId");
					this.Ontbl_Server_DBDetailsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Server_FTP_AccountId_Local", DbType="Int")]
		public System.Nullable<int> tbl_Server_FTP_AccountId_Local
		{
			get
			{
				return this._tbl_Server_FTP_AccountId_Local;
			}
			set
			{
				if ((this._tbl_Server_FTP_AccountId_Local != value))
				{
					if (this._tbl_Server_FTP_Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontbl_Server_FTP_AccountId_LocalChanging(value);
					this.SendPropertyChanging();
					this._tbl_Server_FTP_AccountId_Local = value;
					this.SendPropertyChanged("tbl_Server_FTP_AccountId_Local");
					this.Ontbl_Server_FTP_AccountId_LocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Server_FTP_AccountId_Remote", DbType="Int")]
		public System.Nullable<int> tbl_Server_FTP_AccountId_Remote
		{
			get
			{
				return this._tbl_Server_FTP_AccountId_Remote;
			}
			set
			{
				if ((this._tbl_Server_FTP_AccountId_Remote != value))
				{
					if (this._tbl_Server_FTP_Account1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontbl_Server_FTP_AccountId_RemoteChanging(value);
					this.SendPropertyChanging();
					this._tbl_Server_FTP_AccountId_Remote = value;
					this.SendPropertyChanged("tbl_Server_FTP_AccountId_Remote");
					this.Ontbl_Server_FTP_AccountId_RemoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Server_ArchiveFilesId", DbType="Int")]
		public System.Nullable<int> tbl_Server_ArchiveFilesId
		{
			get
			{
				return this._tbl_Server_ArchiveFilesId;
			}
			set
			{
				if ((this._tbl_Server_ArchiveFilesId != value))
				{
					this.Ontbl_Server_ArchiveFilesIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Server_ArchiveFilesId = value;
					this.SendPropertyChanged("tbl_Server_ArchiveFilesId");
					this.Ontbl_Server_ArchiveFilesIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_ContactFrequencyID", DbType="Int")]
		public System.Nullable<int> tbl_ContactFrequencyID
		{
			get
			{
				return this._tbl_ContactFrequencyID;
			}
			set
			{
				if ((this._tbl_ContactFrequencyID != value))
				{
					this.Ontbl_ContactFrequencyIDChanging(value);
					this.SendPropertyChanging();
					this._tbl_ContactFrequencyID = value;
					this.SendPropertyChanged("tbl_ContactFrequencyID");
					this.Ontbl_ContactFrequencyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Site_tbl_Site_Enterprise", Storage="_tbl_Site_Enterprises", ThisKey="tbl_SiteId", OtherKey="tbl_SiteId")]
		public EntitySet<tbl_Site_Enterprise> tbl_Site_Enterprises
		{
			get
			{
				return this._tbl_Site_Enterprises;
			}
			set
			{
				this._tbl_Site_Enterprises.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Site_tbl_Site_XSI_Detail", Storage="_tbl_Site_XSI_Details", ThisKey="tbl_SiteId", OtherKey="tbl_SiteId")]
		public EntitySet<tbl_Site_XSI_Detail> tbl_Site_XSI_Details
		{
			get
			{
				return this._tbl_Site_XSI_Details;
			}
			set
			{
				this._tbl_Site_XSI_Details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Site_tbl_Site_UnitType", Storage="_tbl_Site_UnitTypes", ThisKey="tbl_SiteId", OtherKey="tbl_SiteId")]
		public EntitySet<tbl_Site_UnitType> tbl_Site_UnitTypes
		{
			get
			{
				return this._tbl_Site_UnitTypes;
			}
			set
			{
				this._tbl_Site_UnitTypes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Site_tbl_Job_PND", Storage="_tbl_Job_PNDs", ThisKey="tbl_SiteId", OtherKey="tbl_SiteId")]
		public EntitySet<tbl_Job_PND> tbl_Job_PNDs
		{
			get
			{
				return this._tbl_Job_PNDs;
			}
			set
			{
				this._tbl_Job_PNDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Company_tbl_Site", Storage="_tbl_Company", ThisKey="tbl_companyId", OtherKey="tbl_CompanyId", IsForeignKey=true)]
		public tbl_Company tbl_Company
		{
			get
			{
				return this._tbl_Company.Entity;
			}
			set
			{
				tbl_Company previousValue = this._tbl_Company.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Company.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Company.Entity = null;
						previousValue.tbl_Sites.Remove(this);
					}
					this._tbl_Company.Entity = value;
					if ((value != null))
					{
						value.tbl_Sites.Add(this);
						this._tbl_companyId = value.tbl_CompanyId;
					}
					else
					{
						this._tbl_companyId = default(int);
					}
					this.SendPropertyChanged("tbl_Company");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Server_FTP_Account_tbl_Site", Storage="_tbl_Server_FTP_Account", ThisKey="tbl_Server_FTP_AccountId_Local", OtherKey="tbl_Server_FTP_AccountId", IsForeignKey=true)]
		public tbl_Server_FTP_Account tbl_Server_FTP_Account
		{
			get
			{
				return this._tbl_Server_FTP_Account.Entity;
			}
			set
			{
				tbl_Server_FTP_Account previousValue = this._tbl_Server_FTP_Account.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Server_FTP_Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Server_FTP_Account.Entity = null;
						previousValue.tbl_Sites.Remove(this);
					}
					this._tbl_Server_FTP_Account.Entity = value;
					if ((value != null))
					{
						value.tbl_Sites.Add(this);
						this._tbl_Server_FTP_AccountId_Local = value.tbl_Server_FTP_AccountId;
					}
					else
					{
						this._tbl_Server_FTP_AccountId_Local = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Server_FTP_Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Server_FTP_Account_tbl_Site1", Storage="_tbl_Server_FTP_Account1", ThisKey="tbl_Server_FTP_AccountId_Remote", OtherKey="tbl_Server_FTP_AccountId", IsForeignKey=true)]
		public tbl_Server_FTP_Account tbl_Server_FTP_Account1
		{
			get
			{
				return this._tbl_Server_FTP_Account1.Entity;
			}
			set
			{
				tbl_Server_FTP_Account previousValue = this._tbl_Server_FTP_Account1.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Server_FTP_Account1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Server_FTP_Account1.Entity = null;
						previousValue.tbl_Sites1.Remove(this);
					}
					this._tbl_Server_FTP_Account1.Entity = value;
					if ((value != null))
					{
						value.tbl_Sites1.Add(this);
						this._tbl_Server_FTP_AccountId_Remote = value.tbl_Server_FTP_AccountId;
					}
					else
					{
						this._tbl_Server_FTP_AccountId_Remote = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Server_FTP_Account1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Site_Enterprises(tbl_Site_Enterprise entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Site = this;
		}
		
		private void detach_tbl_Site_Enterprises(tbl_Site_Enterprise entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Site = null;
		}
		
		private void attach_tbl_Site_XSI_Details(tbl_Site_XSI_Detail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Site = this;
		}
		
		private void detach_tbl_Site_XSI_Details(tbl_Site_XSI_Detail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Site = null;
		}
		
		private void attach_tbl_Site_UnitTypes(tbl_Site_UnitType entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Site = this;
		}
		
		private void detach_tbl_Site_UnitTypes(tbl_Site_UnitType entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Site = null;
		}
		
		private void attach_tbl_Job_PNDs(tbl_Job_PND entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Site = this;
		}
		
		private void detach_tbl_Job_PNDs(tbl_Job_PND entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Site = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Site_UnitType")]
	public partial class tbl_Site_UnitType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tbl_Site_UnitTypeId;
		
		private int _tbl_SiteId;
		
		private int _tbl_UnitTypeId;
		
		private System.DateTime _tbl_Site_UnitType_ValidFrom;
		
		private System.Nullable<System.DateTime> _tbl_Site_UnitType_ValidTo;
		
		private EntityRef<tbl_Site> _tbl_Site;
		
		private EntityRef<tbl_UnitType> _tbl_UnitType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontbl_Site_UnitTypeIdChanging(int value);
    partial void Ontbl_Site_UnitTypeIdChanged();
    partial void Ontbl_SiteIdChanging(int value);
    partial void Ontbl_SiteIdChanged();
    partial void Ontbl_UnitTypeIdChanging(int value);
    partial void Ontbl_UnitTypeIdChanged();
    partial void Ontbl_Site_UnitType_ValidFromChanging(System.DateTime value);
    partial void Ontbl_Site_UnitType_ValidFromChanged();
    partial void Ontbl_Site_UnitType_ValidToChanging(System.Nullable<System.DateTime> value);
    partial void Ontbl_Site_UnitType_ValidToChanged();
    #endregion
		
		public tbl_Site_UnitType()
		{
			this._tbl_Site = default(EntityRef<tbl_Site>);
			this._tbl_UnitType = default(EntityRef<tbl_UnitType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_UnitTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tbl_Site_UnitTypeId
		{
			get
			{
				return this._tbl_Site_UnitTypeId;
			}
			set
			{
				if ((this._tbl_Site_UnitTypeId != value))
				{
					this.Ontbl_Site_UnitTypeIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_UnitTypeId = value;
					this.SendPropertyChanged("tbl_Site_UnitTypeId");
					this.Ontbl_Site_UnitTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_SiteId", DbType="Int NOT NULL")]
		public int tbl_SiteId
		{
			get
			{
				return this._tbl_SiteId;
			}
			set
			{
				if ((this._tbl_SiteId != value))
				{
					if (this._tbl_Site.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontbl_SiteIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_SiteId = value;
					this.SendPropertyChanged("tbl_SiteId");
					this.Ontbl_SiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_UnitTypeId", DbType="Int NOT NULL")]
		public int tbl_UnitTypeId
		{
			get
			{
				return this._tbl_UnitTypeId;
			}
			set
			{
				if ((this._tbl_UnitTypeId != value))
				{
					if (this._tbl_UnitType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontbl_UnitTypeIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_UnitTypeId = value;
					this.SendPropertyChanged("tbl_UnitTypeId");
					this.Ontbl_UnitTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_UnitType_ValidFrom", DbType="DateTime NOT NULL")]
		public System.DateTime tbl_Site_UnitType_ValidFrom
		{
			get
			{
				return this._tbl_Site_UnitType_ValidFrom;
			}
			set
			{
				if ((this._tbl_Site_UnitType_ValidFrom != value))
				{
					this.Ontbl_Site_UnitType_ValidFromChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_UnitType_ValidFrom = value;
					this.SendPropertyChanged("tbl_Site_UnitType_ValidFrom");
					this.Ontbl_Site_UnitType_ValidFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_UnitType_ValidTo", DbType="DateTime")]
		public System.Nullable<System.DateTime> tbl_Site_UnitType_ValidTo
		{
			get
			{
				return this._tbl_Site_UnitType_ValidTo;
			}
			set
			{
				if ((this._tbl_Site_UnitType_ValidTo != value))
				{
					this.Ontbl_Site_UnitType_ValidToChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_UnitType_ValidTo = value;
					this.SendPropertyChanged("tbl_Site_UnitType_ValidTo");
					this.Ontbl_Site_UnitType_ValidToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Site_tbl_Site_UnitType", Storage="_tbl_Site", ThisKey="tbl_SiteId", OtherKey="tbl_SiteId", IsForeignKey=true)]
		public tbl_Site tbl_Site
		{
			get
			{
				return this._tbl_Site.Entity;
			}
			set
			{
				tbl_Site previousValue = this._tbl_Site.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Site.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Site.Entity = null;
						previousValue.tbl_Site_UnitTypes.Remove(this);
					}
					this._tbl_Site.Entity = value;
					if ((value != null))
					{
						value.tbl_Site_UnitTypes.Add(this);
						this._tbl_SiteId = value.tbl_SiteId;
					}
					else
					{
						this._tbl_SiteId = default(int);
					}
					this.SendPropertyChanged("tbl_Site");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UnitType_tbl_Site_UnitType", Storage="_tbl_UnitType", ThisKey="tbl_UnitTypeId", OtherKey="tbl_UnitTypeId", IsForeignKey=true)]
		public tbl_UnitType tbl_UnitType
		{
			get
			{
				return this._tbl_UnitType.Entity;
			}
			set
			{
				tbl_UnitType previousValue = this._tbl_UnitType.Entity;
				if (((previousValue != value) 
							|| (this._tbl_UnitType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_UnitType.Entity = null;
						previousValue.tbl_Site_UnitTypes.Remove(this);
					}
					this._tbl_UnitType.Entity = value;
					if ((value != null))
					{
						value.tbl_Site_UnitTypes.Add(this);
						this._tbl_UnitTypeId = value.tbl_UnitTypeId;
					}
					else
					{
						this._tbl_UnitTypeId = default(int);
					}
					this.SendPropertyChanged("tbl_UnitType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_UnitType")]
	public partial class tbl_UnitType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tbl_UnitTypeId;
		
		private System.Nullable<char> _UnitType_SerialClass;
		
		private string _UnitType_Name;
		
		private string _UnitType_Description;
		
		private EntitySet<tbl_Site_UnitType> _tbl_Site_UnitTypes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontbl_UnitTypeIdChanging(int value);
    partial void Ontbl_UnitTypeIdChanged();
    partial void OnUnitType_SerialClassChanging(System.Nullable<char> value);
    partial void OnUnitType_SerialClassChanged();
    partial void OnUnitType_NameChanging(string value);
    partial void OnUnitType_NameChanged();
    partial void OnUnitType_DescriptionChanging(string value);
    partial void OnUnitType_DescriptionChanged();
    #endregion
		
		public tbl_UnitType()
		{
			this._tbl_Site_UnitTypes = new EntitySet<tbl_Site_UnitType>(new Action<tbl_Site_UnitType>(this.attach_tbl_Site_UnitTypes), new Action<tbl_Site_UnitType>(this.detach_tbl_Site_UnitTypes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_UnitTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tbl_UnitTypeId
		{
			get
			{
				return this._tbl_UnitTypeId;
			}
			set
			{
				if ((this._tbl_UnitTypeId != value))
				{
					this.Ontbl_UnitTypeIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_UnitTypeId = value;
					this.SendPropertyChanged("tbl_UnitTypeId");
					this.Ontbl_UnitTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitType_SerialClass", DbType="Char(1)")]
		public System.Nullable<char> UnitType_SerialClass
		{
			get
			{
				return this._UnitType_SerialClass;
			}
			set
			{
				if ((this._UnitType_SerialClass != value))
				{
					this.OnUnitType_SerialClassChanging(value);
					this.SendPropertyChanging();
					this._UnitType_SerialClass = value;
					this.SendPropertyChanged("UnitType_SerialClass");
					this.OnUnitType_SerialClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitType_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UnitType_Name
		{
			get
			{
				return this._UnitType_Name;
			}
			set
			{
				if ((this._UnitType_Name != value))
				{
					this.OnUnitType_NameChanging(value);
					this.SendPropertyChanging();
					this._UnitType_Name = value;
					this.SendPropertyChanged("UnitType_Name");
					this.OnUnitType_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitType_Description", DbType="VarChar(70)")]
		public string UnitType_Description
		{
			get
			{
				return this._UnitType_Description;
			}
			set
			{
				if ((this._UnitType_Description != value))
				{
					this.OnUnitType_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._UnitType_Description = value;
					this.SendPropertyChanged("UnitType_Description");
					this.OnUnitType_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UnitType_tbl_Site_UnitType", Storage="_tbl_Site_UnitTypes", ThisKey="tbl_UnitTypeId", OtherKey="tbl_UnitTypeId")]
		public EntitySet<tbl_Site_UnitType> tbl_Site_UnitTypes
		{
			get
			{
				return this._tbl_Site_UnitTypes;
			}
			set
			{
				this._tbl_Site_UnitTypes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Site_UnitTypes(tbl_Site_UnitType entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UnitType = this;
		}
		
		private void detach_tbl_Site_UnitTypes(tbl_Site_UnitType entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UnitType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Job_PND")]
	public partial class tbl_Job_PND : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tbl_Job_PNDId;
		
		private int _tbl_BatchFileId;
		
		private int _tbl_SiteId;
		
		private System.DateTime _Job_PND_CreatedTime;
		
		private EntityRef<tbl_Site> _tbl_Site;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontbl_Job_PNDIdChanging(int value);
    partial void Ontbl_Job_PNDIdChanged();
    partial void Ontbl_BatchFileIdChanging(int value);
    partial void Ontbl_BatchFileIdChanged();
    partial void Ontbl_SiteIdChanging(int value);
    partial void Ontbl_SiteIdChanged();
    partial void OnJob_PND_CreatedTimeChanging(System.DateTime value);
    partial void OnJob_PND_CreatedTimeChanged();
    #endregion
		
		public tbl_Job_PND()
		{
			this._tbl_Site = default(EntityRef<tbl_Site>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Job_PNDId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tbl_Job_PNDId
		{
			get
			{
				return this._tbl_Job_PNDId;
			}
			set
			{
				if ((this._tbl_Job_PNDId != value))
				{
					this.Ontbl_Job_PNDIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Job_PNDId = value;
					this.SendPropertyChanged("tbl_Job_PNDId");
					this.Ontbl_Job_PNDIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_BatchFileId", DbType="Int NOT NULL")]
		public int tbl_BatchFileId
		{
			get
			{
				return this._tbl_BatchFileId;
			}
			set
			{
				if ((this._tbl_BatchFileId != value))
				{
					this.Ontbl_BatchFileIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_BatchFileId = value;
					this.SendPropertyChanged("tbl_BatchFileId");
					this.Ontbl_BatchFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_SiteId", DbType="Int NOT NULL")]
		public int tbl_SiteId
		{
			get
			{
				return this._tbl_SiteId;
			}
			set
			{
				if ((this._tbl_SiteId != value))
				{
					if (this._tbl_Site.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontbl_SiteIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_SiteId = value;
					this.SendPropertyChanged("tbl_SiteId");
					this.Ontbl_SiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job_PND_CreatedTime", DbType="DateTime NOT NULL")]
		public System.DateTime Job_PND_CreatedTime
		{
			get
			{
				return this._Job_PND_CreatedTime;
			}
			set
			{
				if ((this._Job_PND_CreatedTime != value))
				{
					this.OnJob_PND_CreatedTimeChanging(value);
					this.SendPropertyChanging();
					this._Job_PND_CreatedTime = value;
					this.SendPropertyChanged("Job_PND_CreatedTime");
					this.OnJob_PND_CreatedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Site_tbl_Job_PND", Storage="_tbl_Site", ThisKey="tbl_SiteId", OtherKey="tbl_SiteId", IsForeignKey=true)]
		public tbl_Site tbl_Site
		{
			get
			{
				return this._tbl_Site.Entity;
			}
			set
			{
				tbl_Site previousValue = this._tbl_Site.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Site.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Site.Entity = null;
						previousValue.tbl_Job_PNDs.Remove(this);
					}
					this._tbl_Site.Entity = value;
					if ((value != null))
					{
						value.tbl_Job_PNDs.Add(this);
						this._tbl_SiteId = value.tbl_SiteId;
					}
					else
					{
						this._tbl_SiteId = default(int);
					}
					this.SendPropertyChanged("tbl_Site");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Site_Community")]
	public partial class tbl_Site_Community : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tbl_Site_CommunityId;
		
		private int _tbl_SiteId;
		
		private string _ComunityId;
		
		private bool _tbl_Site_Community_active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontbl_Site_CommunityIdChanging(int value);
    partial void Ontbl_Site_CommunityIdChanged();
    partial void Ontbl_SiteIdChanging(int value);
    partial void Ontbl_SiteIdChanged();
    partial void OnComunityIdChanging(string value);
    partial void OnComunityIdChanged();
    partial void Ontbl_Site_Community_activeChanging(bool value);
    partial void Ontbl_Site_Community_activeChanged();
    #endregion
		
		public tbl_Site_Community()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_CommunityId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tbl_Site_CommunityId
		{
			get
			{
				return this._tbl_Site_CommunityId;
			}
			set
			{
				if ((this._tbl_Site_CommunityId != value))
				{
					this.Ontbl_Site_CommunityIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_CommunityId = value;
					this.SendPropertyChanged("tbl_Site_CommunityId");
					this.Ontbl_Site_CommunityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_SiteId", DbType="Int NOT NULL")]
		public int tbl_SiteId
		{
			get
			{
				return this._tbl_SiteId;
			}
			set
			{
				if ((this._tbl_SiteId != value))
				{
					this.Ontbl_SiteIdChanging(value);
					this.SendPropertyChanging();
					this._tbl_SiteId = value;
					this.SendPropertyChanged("tbl_SiteId");
					this.Ontbl_SiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunityId", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string ComunityId
		{
			get
			{
				return this._ComunityId;
			}
			set
			{
				if ((this._ComunityId != value))
				{
					this.OnComunityIdChanging(value);
					this.SendPropertyChanging();
					this._ComunityId = value;
					this.SendPropertyChanged("ComunityId");
					this.OnComunityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Site_Community_active", DbType="Bit NOT NULL")]
		public bool tbl_Site_Community_active
		{
			get
			{
				return this._tbl_Site_Community_active;
			}
			set
			{
				if ((this._tbl_Site_Community_active != value))
				{
					this.Ontbl_Site_Community_activeChanging(value);
					this.SendPropertyChanging();
					this._tbl_Site_Community_active = value;
					this.SendPropertyChanged("tbl_Site_Community_active");
					this.Ontbl_Site_Community_activeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
