#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVProcessor.Database.Tables
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Centile")]
	public partial class CentileDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_company(tbl_company instance);
    partial void Updatetbl_company(tbl_company instance);
    partial void Deletetbl_company(tbl_company instance);
    partial void Inserttbl_site(tbl_site instance);
    partial void Updatetbl_site(tbl_site instance);
    partial void Deletetbl_site(tbl_site instance);
    partial void InsertDirectory(Directory instance);
    partial void UpdateDirectory(Directory instance);
    partial void DeleteDirectory(Directory instance);
    partial void Inserttbl_branding(tbl_branding instance);
    partial void Updatetbl_branding(tbl_branding instance);
    partial void Deletetbl_branding(tbl_branding instance);
    partial void Inserttbl_email(tbl_email instance);
    partial void Updatetbl_email(tbl_email instance);
    partial void Deletetbl_email(tbl_email instance);
    #endregion
		
		public CentileDataContext() : 
				base(global::CSVProcessor.Database.Properties.Settings.Default.CentileConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public CentileDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CentileDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CentileDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CentileDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_company> tbl_companies
		{
			get
			{
				return this.GetTable<tbl_company>();
			}
		}
		
		public System.Data.Linq.Table<tbl_site> tbl_sites
		{
			get
			{
				return this.GetTable<tbl_site>();
			}
		}
		
		public System.Data.Linq.Table<tbl_infeed> tbl_infeeds
		{
			get
			{
				return this.GetTable<tbl_infeed>();
			}
		}
		
		public System.Data.Linq.Table<tbl_outfeed> tbl_outfeeds
		{
			get
			{
				return this.GetTable<tbl_outfeed>();
			}
		}
		
		public System.Data.Linq.Table<Directory> Directories
		{
			get
			{
				return this.GetTable<Directory>();
			}
		}
		
		public System.Data.Linq.Table<tbl_branding> tbl_brandings
		{
			get
			{
				return this.GetTable<tbl_branding>();
			}
		}
		
		public System.Data.Linq.Table<tbl_email> tbl_emails
		{
			get
			{
				return this.GetTable<tbl_email>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_company")]
	public partial class tbl_company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _company_id_PK;
		
		private string _company_name;
		
		private System.Nullable<int> _address_id_PK;
		
		private System.Nullable<int> _branding_id;
		
		private System.Nullable<int> _tbl_company_level_id_PK;
		
		private string _tbl_Centile_Community_id_FK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncompany_id_PKChanging(int value);
    partial void Oncompany_id_PKChanged();
    partial void Oncompany_nameChanging(string value);
    partial void Oncompany_nameChanged();
    partial void Onaddress_id_PKChanging(System.Nullable<int> value);
    partial void Onaddress_id_PKChanged();
    partial void Onbranding_idChanging(System.Nullable<int> value);
    partial void Onbranding_idChanged();
    partial void Ontbl_company_level_id_PKChanging(System.Nullable<int> value);
    partial void Ontbl_company_level_id_PKChanged();
    partial void Ontbl_Centile_Community_id_FKChanging(string value);
    partial void Ontbl_Centile_Community_id_FKChanged();
    #endregion
		
		public tbl_company()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_id_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int company_id_PK
		{
			get
			{
				return this._company_id_PK;
			}
			set
			{
				if ((this._company_id_PK != value))
				{
					this.Oncompany_id_PKChanging(value);
					this.SendPropertyChanging();
					this._company_id_PK = value;
					this.SendPropertyChanged("company_id_PK");
					this.Oncompany_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="VarChar(50)")]
		public string company_name
		{
			get
			{
				return this._company_name;
			}
			set
			{
				if ((this._company_name != value))
				{
					this.Oncompany_nameChanging(value);
					this.SendPropertyChanging();
					this._company_name = value;
					this.SendPropertyChanged("company_name");
					this.Oncompany_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_id_PK", DbType="Int")]
		public System.Nullable<int> address_id_PK
		{
			get
			{
				return this._address_id_PK;
			}
			set
			{
				if ((this._address_id_PK != value))
				{
					this.Onaddress_id_PKChanging(value);
					this.SendPropertyChanging();
					this._address_id_PK = value;
					this.SendPropertyChanged("address_id_PK");
					this.Onaddress_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branding_id", DbType="Int")]
		public System.Nullable<int> branding_id
		{
			get
			{
				return this._branding_id;
			}
			set
			{
				if ((this._branding_id != value))
				{
					this.Onbranding_idChanging(value);
					this.SendPropertyChanging();
					this._branding_id = value;
					this.SendPropertyChanged("branding_id");
					this.Onbranding_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_company_level_id_PK", DbType="Int")]
		public System.Nullable<int> tbl_company_level_id_PK
		{
			get
			{
				return this._tbl_company_level_id_PK;
			}
			set
			{
				if ((this._tbl_company_level_id_PK != value))
				{
					this.Ontbl_company_level_id_PKChanging(value);
					this.SendPropertyChanging();
					this._tbl_company_level_id_PK = value;
					this.SendPropertyChanged("tbl_company_level_id_PK");
					this.Ontbl_company_level_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Centile_Community_id_FK", DbType="VarChar(150)")]
		public string tbl_Centile_Community_id_FK
		{
			get
			{
				return this._tbl_Centile_Community_id_FK;
			}
			set
			{
				if ((this._tbl_Centile_Community_id_FK != value))
				{
					this.Ontbl_Centile_Community_id_FKChanging(value);
					this.SendPropertyChanging();
					this._tbl_Centile_Community_id_FK = value;
					this.SendPropertyChanged("tbl_Centile_Community_id_FK");
					this.Ontbl_Centile_Community_id_FKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_site")]
	public partial class tbl_site : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _site_id_PK;
		
		private System.Nullable<int> _site_number;
		
		private string _site_name;
		
		private string _site_type;
		
		private System.Nullable<int> _site_userlimit;
		
		private System.Nullable<System.DateTime> _site_lastinfeedmodifieddate;
		
		private string _site_lastinfeeddirectory;
		
		private System.Nullable<long> _site_lastinfeedreadrow;
		
		private System.Nullable<System.DateTime> _site_lastoutfeedmodifieddate;
		
		private string _site_lastoutfeeddirectory;
		
		private System.Nullable<long> _site_lastoutfeedreadrow;
		
		private System.Nullable<int> _company_id_PK;
		
		private System.Nullable<int> _address_id_PK;
		
		private System.Nullable<int> _site_datadropfrequency;
		
		private System.Nullable<bool> _Site_termsandconditions;
		
		private System.Nullable<bool> _Site_LyncSwitch;
		
		private string _Site_SwitchName;
		
		private string _Site_LyncDomain;
		
		private string _tbl_Centile_Community_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsite_id_PKChanging(int value);
    partial void Onsite_id_PKChanged();
    partial void Onsite_numberChanging(System.Nullable<int> value);
    partial void Onsite_numberChanged();
    partial void Onsite_nameChanging(string value);
    partial void Onsite_nameChanged();
    partial void Onsite_typeChanging(string value);
    partial void Onsite_typeChanged();
    partial void Onsite_userlimitChanging(System.Nullable<int> value);
    partial void Onsite_userlimitChanged();
    partial void Onsite_lastinfeedmodifieddateChanging(System.Nullable<System.DateTime> value);
    partial void Onsite_lastinfeedmodifieddateChanged();
    partial void Onsite_lastinfeeddirectoryChanging(string value);
    partial void Onsite_lastinfeeddirectoryChanged();
    partial void Onsite_lastinfeedreadrowChanging(System.Nullable<long> value);
    partial void Onsite_lastinfeedreadrowChanged();
    partial void Onsite_lastoutfeedmodifieddateChanging(System.Nullable<System.DateTime> value);
    partial void Onsite_lastoutfeedmodifieddateChanged();
    partial void Onsite_lastoutfeeddirectoryChanging(string value);
    partial void Onsite_lastoutfeeddirectoryChanged();
    partial void Onsite_lastoutfeedreadrowChanging(System.Nullable<long> value);
    partial void Onsite_lastoutfeedreadrowChanged();
    partial void Oncompany_id_PKChanging(System.Nullable<int> value);
    partial void Oncompany_id_PKChanged();
    partial void Onaddress_id_PKChanging(System.Nullable<int> value);
    partial void Onaddress_id_PKChanged();
    partial void Onsite_datadropfrequencyChanging(System.Nullable<int> value);
    partial void Onsite_datadropfrequencyChanged();
    partial void OnSite_termsandconditionsChanging(System.Nullable<bool> value);
    partial void OnSite_termsandconditionsChanged();
    partial void OnSite_LyncSwitchChanging(System.Nullable<bool> value);
    partial void OnSite_LyncSwitchChanged();
    partial void OnSite_SwitchNameChanging(string value);
    partial void OnSite_SwitchNameChanged();
    partial void OnSite_LyncDomainChanging(string value);
    partial void OnSite_LyncDomainChanged();
    partial void Ontbl_Centile_Community_IdChanging(string value);
    partial void Ontbl_Centile_Community_IdChanged();
    #endregion
		
		public tbl_site()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_id_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int site_id_PK
		{
			get
			{
				return this._site_id_PK;
			}
			set
			{
				if ((this._site_id_PK != value))
				{
					this.Onsite_id_PKChanging(value);
					this.SendPropertyChanging();
					this._site_id_PK = value;
					this.SendPropertyChanged("site_id_PK");
					this.Onsite_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_number", DbType="Int")]
		public System.Nullable<int> site_number
		{
			get
			{
				return this._site_number;
			}
			set
			{
				if ((this._site_number != value))
				{
					this.Onsite_numberChanging(value);
					this.SendPropertyChanging();
					this._site_number = value;
					this.SendPropertyChanged("site_number");
					this.Onsite_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_name", DbType="VarChar(250)")]
		public string site_name
		{
			get
			{
				return this._site_name;
			}
			set
			{
				if ((this._site_name != value))
				{
					this.Onsite_nameChanging(value);
					this.SendPropertyChanging();
					this._site_name = value;
					this.SendPropertyChanged("site_name");
					this.Onsite_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_type", DbType="NVarChar(50)")]
		public string site_type
		{
			get
			{
				return this._site_type;
			}
			set
			{
				if ((this._site_type != value))
				{
					this.Onsite_typeChanging(value);
					this.SendPropertyChanging();
					this._site_type = value;
					this.SendPropertyChanged("site_type");
					this.Onsite_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_userlimit", DbType="Int")]
		public System.Nullable<int> site_userlimit
		{
			get
			{
				return this._site_userlimit;
			}
			set
			{
				if ((this._site_userlimit != value))
				{
					this.Onsite_userlimitChanging(value);
					this.SendPropertyChanging();
					this._site_userlimit = value;
					this.SendPropertyChanged("site_userlimit");
					this.Onsite_userlimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastinfeedmodifieddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> site_lastinfeedmodifieddate
		{
			get
			{
				return this._site_lastinfeedmodifieddate;
			}
			set
			{
				if ((this._site_lastinfeedmodifieddate != value))
				{
					this.Onsite_lastinfeedmodifieddateChanging(value);
					this.SendPropertyChanging();
					this._site_lastinfeedmodifieddate = value;
					this.SendPropertyChanged("site_lastinfeedmodifieddate");
					this.Onsite_lastinfeedmodifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastinfeeddirectory", DbType="VarChar(100)")]
		public string site_lastinfeeddirectory
		{
			get
			{
				return this._site_lastinfeeddirectory;
			}
			set
			{
				if ((this._site_lastinfeeddirectory != value))
				{
					this.Onsite_lastinfeeddirectoryChanging(value);
					this.SendPropertyChanging();
					this._site_lastinfeeddirectory = value;
					this.SendPropertyChanged("site_lastinfeeddirectory");
					this.Onsite_lastinfeeddirectoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastinfeedreadrow", DbType="BigInt")]
		public System.Nullable<long> site_lastinfeedreadrow
		{
			get
			{
				return this._site_lastinfeedreadrow;
			}
			set
			{
				if ((this._site_lastinfeedreadrow != value))
				{
					this.Onsite_lastinfeedreadrowChanging(value);
					this.SendPropertyChanging();
					this._site_lastinfeedreadrow = value;
					this.SendPropertyChanged("site_lastinfeedreadrow");
					this.Onsite_lastinfeedreadrowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastoutfeedmodifieddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> site_lastoutfeedmodifieddate
		{
			get
			{
				return this._site_lastoutfeedmodifieddate;
			}
			set
			{
				if ((this._site_lastoutfeedmodifieddate != value))
				{
					this.Onsite_lastoutfeedmodifieddateChanging(value);
					this.SendPropertyChanging();
					this._site_lastoutfeedmodifieddate = value;
					this.SendPropertyChanged("site_lastoutfeedmodifieddate");
					this.Onsite_lastoutfeedmodifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastoutfeeddirectory", DbType="VarChar(100)")]
		public string site_lastoutfeeddirectory
		{
			get
			{
				return this._site_lastoutfeeddirectory;
			}
			set
			{
				if ((this._site_lastoutfeeddirectory != value))
				{
					this.Onsite_lastoutfeeddirectoryChanging(value);
					this.SendPropertyChanging();
					this._site_lastoutfeeddirectory = value;
					this.SendPropertyChanged("site_lastoutfeeddirectory");
					this.Onsite_lastoutfeeddirectoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastoutfeedreadrow", DbType="BigInt")]
		public System.Nullable<long> site_lastoutfeedreadrow
		{
			get
			{
				return this._site_lastoutfeedreadrow;
			}
			set
			{
				if ((this._site_lastoutfeedreadrow != value))
				{
					this.Onsite_lastoutfeedreadrowChanging(value);
					this.SendPropertyChanging();
					this._site_lastoutfeedreadrow = value;
					this.SendPropertyChanged("site_lastoutfeedreadrow");
					this.Onsite_lastoutfeedreadrowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_id_PK", DbType="Int")]
		public System.Nullable<int> company_id_PK
		{
			get
			{
				return this._company_id_PK;
			}
			set
			{
				if ((this._company_id_PK != value))
				{
					this.Oncompany_id_PKChanging(value);
					this.SendPropertyChanging();
					this._company_id_PK = value;
					this.SendPropertyChanged("company_id_PK");
					this.Oncompany_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_id_PK", DbType="Int")]
		public System.Nullable<int> address_id_PK
		{
			get
			{
				return this._address_id_PK;
			}
			set
			{
				if ((this._address_id_PK != value))
				{
					this.Onaddress_id_PKChanging(value);
					this.SendPropertyChanging();
					this._address_id_PK = value;
					this.SendPropertyChanged("address_id_PK");
					this.Onaddress_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_datadropfrequency", DbType="Int")]
		public System.Nullable<int> site_datadropfrequency
		{
			get
			{
				return this._site_datadropfrequency;
			}
			set
			{
				if ((this._site_datadropfrequency != value))
				{
					this.Onsite_datadropfrequencyChanging(value);
					this.SendPropertyChanging();
					this._site_datadropfrequency = value;
					this.SendPropertyChanged("site_datadropfrequency");
					this.Onsite_datadropfrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_termsandconditions", DbType="Bit")]
		public System.Nullable<bool> Site_termsandconditions
		{
			get
			{
				return this._Site_termsandconditions;
			}
			set
			{
				if ((this._Site_termsandconditions != value))
				{
					this.OnSite_termsandconditionsChanging(value);
					this.SendPropertyChanging();
					this._Site_termsandconditions = value;
					this.SendPropertyChanged("Site_termsandconditions");
					this.OnSite_termsandconditionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_LyncSwitch", DbType="Bit")]
		public System.Nullable<bool> Site_LyncSwitch
		{
			get
			{
				return this._Site_LyncSwitch;
			}
			set
			{
				if ((this._Site_LyncSwitch != value))
				{
					this.OnSite_LyncSwitchChanging(value);
					this.SendPropertyChanging();
					this._Site_LyncSwitch = value;
					this.SendPropertyChanged("Site_LyncSwitch");
					this.OnSite_LyncSwitchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_SwitchName", DbType="VarChar(50)")]
		public string Site_SwitchName
		{
			get
			{
				return this._Site_SwitchName;
			}
			set
			{
				if ((this._Site_SwitchName != value))
				{
					this.OnSite_SwitchNameChanging(value);
					this.SendPropertyChanging();
					this._Site_SwitchName = value;
					this.SendPropertyChanged("Site_SwitchName");
					this.OnSite_SwitchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_LyncDomain", DbType="VarChar(50)")]
		public string Site_LyncDomain
		{
			get
			{
				return this._Site_LyncDomain;
			}
			set
			{
				if ((this._Site_LyncDomain != value))
				{
					this.OnSite_LyncDomainChanging(value);
					this.SendPropertyChanging();
					this._Site_LyncDomain = value;
					this.SendPropertyChanged("Site_LyncDomain");
					this.OnSite_LyncDomainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Centile_Community_Id", DbType="VarChar(150)")]
		public string tbl_Centile_Community_Id
		{
			get
			{
				return this._tbl_Centile_Community_Id;
			}
			set
			{
				if ((this._tbl_Centile_Community_Id != value))
				{
					this.Ontbl_Centile_Community_IdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Centile_Community_Id = value;
					this.SendPropertyChanged("tbl_Centile_Community_Id");
					this.Ontbl_Centile_Community_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_infeed")]
	public partial class tbl_infeed
	{
		
		private int _infeed_site_id_FK;
		
		private System.Nullable<char> _infeed_versionnum;
		
		private System.DateTime _infeed_startdatetime;
		
		private System.Nullable<System.DateTime> _infeed_pabxstartdatetime;
		
		private string _infeed_firstextension;
		
		private string _infeed_secondextension;
		
		private string _infeed_callednumber;
		
		private string _infeed_accountnumber;
		
		private string _infeed_originatortrunkgroup;
		
		private string _infeed_originatortrunknumber;
		
		private System.Nullable<int> _infeed_connectduration;
		
		private System.Nullable<int> _infeed_ringduration;
		
		private System.Nullable<int> _infeed_waitduration;
		
		private string _infeed_callingnumber;
		
		private System.Nullable<int> _infeed_destinationpointer;
		
		private System.Nullable<char> _infeed_codelength;
		
		private string _infeed_calltype;
		
		private System.Nullable<int> _infeed_flags;
		
		private string _infeed_installationid;
		
		private string _infeed_contactid;
		
		private System.Nullable<int> _infeed_allocationtype;
		
		private System.Nullable<int> _infeed_destinationtype_int;
		
		private int _infeed_id_PK;
		
		private string _infeed_callingPartition;
		
		private string _infeed_calledPartition;
		
		private System.Nullable<int> _infeed_QOS_Callid;
		
		private System.Nullable<int> _Infeed_OQS_SequenceID;
		
		private string _infeed_calledDeviceID;
		
		private string _infeed_callingDeviceID;
		
		private System.Nullable<int> _infeed_QOS_callLeg_id;
		
		private System.Nullable<System.DateTime> _infeed_endDateTime;
		
		private string _infeed_calledname;
		
		private string _infeed_callername;
		
		private string _infeed_departmentname;
		
		private string _infeed_communityId;
		
		public tbl_infeed()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_site_id_FK", DbType="Int NOT NULL")]
		public int infeed_site_id_FK
		{
			get
			{
				return this._infeed_site_id_FK;
			}
			set
			{
				if ((this._infeed_site_id_FK != value))
				{
					this._infeed_site_id_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_versionnum", DbType="Char(1)")]
		public System.Nullable<char> infeed_versionnum
		{
			get
			{
				return this._infeed_versionnum;
			}
			set
			{
				if ((this._infeed_versionnum != value))
				{
					this._infeed_versionnum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_startdatetime", DbType="DateTime NOT NULL")]
		public System.DateTime infeed_startdatetime
		{
			get
			{
				return this._infeed_startdatetime;
			}
			set
			{
				if ((this._infeed_startdatetime != value))
				{
					this._infeed_startdatetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_pabxstartdatetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> infeed_pabxstartdatetime
		{
			get
			{
				return this._infeed_pabxstartdatetime;
			}
			set
			{
				if ((this._infeed_pabxstartdatetime != value))
				{
					this._infeed_pabxstartdatetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_firstextension", DbType="VarChar(100)")]
		public string infeed_firstextension
		{
			get
			{
				return this._infeed_firstextension;
			}
			set
			{
				if ((this._infeed_firstextension != value))
				{
					this._infeed_firstextension = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_secondextension", DbType="VarChar(100)")]
		public string infeed_secondextension
		{
			get
			{
				return this._infeed_secondextension;
			}
			set
			{
				if ((this._infeed_secondextension != value))
				{
					this._infeed_secondextension = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_callednumber", DbType="VarChar(18)")]
		public string infeed_callednumber
		{
			get
			{
				return this._infeed_callednumber;
			}
			set
			{
				if ((this._infeed_callednumber != value))
				{
					this._infeed_callednumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_accountnumber", DbType="VarChar(25)")]
		public string infeed_accountnumber
		{
			get
			{
				return this._infeed_accountnumber;
			}
			set
			{
				if ((this._infeed_accountnumber != value))
				{
					this._infeed_accountnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_originatortrunkgroup", DbType="VarChar(25)")]
		public string infeed_originatortrunkgroup
		{
			get
			{
				return this._infeed_originatortrunkgroup;
			}
			set
			{
				if ((this._infeed_originatortrunkgroup != value))
				{
					this._infeed_originatortrunkgroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_originatortrunknumber", DbType="VarChar(25)")]
		public string infeed_originatortrunknumber
		{
			get
			{
				return this._infeed_originatortrunknumber;
			}
			set
			{
				if ((this._infeed_originatortrunknumber != value))
				{
					this._infeed_originatortrunknumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_connectduration", DbType="Int")]
		public System.Nullable<int> infeed_connectduration
		{
			get
			{
				return this._infeed_connectduration;
			}
			set
			{
				if ((this._infeed_connectduration != value))
				{
					this._infeed_connectduration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_ringduration", DbType="Int")]
		public System.Nullable<int> infeed_ringduration
		{
			get
			{
				return this._infeed_ringduration;
			}
			set
			{
				if ((this._infeed_ringduration != value))
				{
					this._infeed_ringduration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_waitduration", DbType="Int")]
		public System.Nullable<int> infeed_waitduration
		{
			get
			{
				return this._infeed_waitduration;
			}
			set
			{
				if ((this._infeed_waitduration != value))
				{
					this._infeed_waitduration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_callingnumber", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string infeed_callingnumber
		{
			get
			{
				return this._infeed_callingnumber;
			}
			set
			{
				if ((this._infeed_callingnumber != value))
				{
					this._infeed_callingnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_destinationpointer", DbType="Int")]
		public System.Nullable<int> infeed_destinationpointer
		{
			get
			{
				return this._infeed_destinationpointer;
			}
			set
			{
				if ((this._infeed_destinationpointer != value))
				{
					this._infeed_destinationpointer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_codelength", DbType="Char(1)")]
		public System.Nullable<char> infeed_codelength
		{
			get
			{
				return this._infeed_codelength;
			}
			set
			{
				if ((this._infeed_codelength != value))
				{
					this._infeed_codelength = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_calltype", DbType="VarChar(2)")]
		public string infeed_calltype
		{
			get
			{
				return this._infeed_calltype;
			}
			set
			{
				if ((this._infeed_calltype != value))
				{
					this._infeed_calltype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_flags", DbType="Int")]
		public System.Nullable<int> infeed_flags
		{
			get
			{
				return this._infeed_flags;
			}
			set
			{
				if ((this._infeed_flags != value))
				{
					this._infeed_flags = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_installationid", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string infeed_installationid
		{
			get
			{
				return this._infeed_installationid;
			}
			set
			{
				if ((this._infeed_installationid != value))
				{
					this._infeed_installationid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_contactid", DbType="VarChar(254) NOT NULL", CanBeNull=false)]
		public string infeed_contactid
		{
			get
			{
				return this._infeed_contactid;
			}
			set
			{
				if ((this._infeed_contactid != value))
				{
					this._infeed_contactid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_allocationtype", DbType="Int")]
		public System.Nullable<int> infeed_allocationtype
		{
			get
			{
				return this._infeed_allocationtype;
			}
			set
			{
				if ((this._infeed_allocationtype != value))
				{
					this._infeed_allocationtype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_destinationtype_int", DbType="Int")]
		public System.Nullable<int> infeed_destinationtype_int
		{
			get
			{
				return this._infeed_destinationtype_int;
			}
			set
			{
				if ((this._infeed_destinationtype_int != value))
				{
					this._infeed_destinationtype_int = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_id_PK", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int infeed_id_PK
		{
			get
			{
				return this._infeed_id_PK;
			}
			set
			{
				if ((this._infeed_id_PK != value))
				{
					this._infeed_id_PK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_callingPartition", DbType="VarChar(200)")]
		public string infeed_callingPartition
		{
			get
			{
				return this._infeed_callingPartition;
			}
			set
			{
				if ((this._infeed_callingPartition != value))
				{
					this._infeed_callingPartition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_calledPartition", DbType="VarChar(200)")]
		public string infeed_calledPartition
		{
			get
			{
				return this._infeed_calledPartition;
			}
			set
			{
				if ((this._infeed_calledPartition != value))
				{
					this._infeed_calledPartition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_QOS_Callid", DbType="Int")]
		public System.Nullable<int> infeed_QOS_Callid
		{
			get
			{
				return this._infeed_QOS_Callid;
			}
			set
			{
				if ((this._infeed_QOS_Callid != value))
				{
					this._infeed_QOS_Callid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Infeed_OQS_SequenceID", DbType="Int")]
		public System.Nullable<int> Infeed_OQS_SequenceID
		{
			get
			{
				return this._Infeed_OQS_SequenceID;
			}
			set
			{
				if ((this._Infeed_OQS_SequenceID != value))
				{
					this._Infeed_OQS_SequenceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_calledDeviceID", DbType="VarChar(250)")]
		public string infeed_calledDeviceID
		{
			get
			{
				return this._infeed_calledDeviceID;
			}
			set
			{
				if ((this._infeed_calledDeviceID != value))
				{
					this._infeed_calledDeviceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_callingDeviceID", DbType="VarChar(250)")]
		public string infeed_callingDeviceID
		{
			get
			{
				return this._infeed_callingDeviceID;
			}
			set
			{
				if ((this._infeed_callingDeviceID != value))
				{
					this._infeed_callingDeviceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_QOS_callLeg_id", DbType="Int")]
		public System.Nullable<int> infeed_QOS_callLeg_id
		{
			get
			{
				return this._infeed_QOS_callLeg_id;
			}
			set
			{
				if ((this._infeed_QOS_callLeg_id != value))
				{
					this._infeed_QOS_callLeg_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_endDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> infeed_endDateTime
		{
			get
			{
				return this._infeed_endDateTime;
			}
			set
			{
				if ((this._infeed_endDateTime != value))
				{
					this._infeed_endDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_calledname", DbType="VarChar(100)")]
		public string infeed_calledname
		{
			get
			{
				return this._infeed_calledname;
			}
			set
			{
				if ((this._infeed_calledname != value))
				{
					this._infeed_calledname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_callername", DbType="VarChar(100)")]
		public string infeed_callername
		{
			get
			{
				return this._infeed_callername;
			}
			set
			{
				if ((this._infeed_callername != value))
				{
					this._infeed_callername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_departmentname", DbType="VarChar(100)")]
		public string infeed_departmentname
		{
			get
			{
				return this._infeed_departmentname;
			}
			set
			{
				if ((this._infeed_departmentname != value))
				{
					this._infeed_departmentname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infeed_communityId", DbType="NVarChar(50)")]
		public string infeed_communityId
		{
			get
			{
				return this._infeed_communityId;
			}
			set
			{
				if ((this._infeed_communityId != value))
				{
					this._infeed_communityId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_outfeed")]
	public partial class tbl_outfeed
	{
		
		private int _outfeed_site_id_FK;
		
		private System.Nullable<char> _outfeed_versionnum;
		
		private System.DateTime _outfeed_startdatetime;
		
		private System.Nullable<System.DateTime> _outfeed_pabxstartdatetime;
		
		private string _outfeed_extensionnumber;
		
		private string _outfeed_trunkaccesscode1;
		
		private string _outfeed_trunkaccesscode2;
		
		private string _outfeed_carrieraccesscode;
		
		private string _outfeed_dialleddigits;
		
		private string _outfeed_accountcode;
		
		private string _outfeed_routename;
		
		private System.Nullable<int> _outfeed_hohduration;
		
		private System.Nullable<int> _outfeed_connectedduration;
		
		private string _outfeed_calltype;
		
		private System.Nullable<int> _outfeed_destinationpointer;
		
		private System.Nullable<char> _outfeed_codelength;
		
		private string _outfeed_originatingtrunkgroup;
		
		private string _outfeed_originatingtrunknumber;
		
		private string _outfeed_outgoingtrunkgroup;
		
		private string _outfeed_outgoingtrunknumber;
		
		private System.Nullable<int> _outfeed_cost;
		
		private System.Nullable<int> _outfeed_alternatecost;
		
		private System.Nullable<int> _outfeed_flags;
		
		private string _outfeed_installationid;
		
		private string _outfeed_contactid;
		
		private System.Nullable<char> _outfeed_padding;
		
		private System.Nullable<int> _outfeed_allocationtype;
		
		private System.Nullable<int> _outfeed_destinationtype_int;
		
		private int _outfeed_id_PK;
		
		private string _outfeed_callingPartition;
		
		private string _outfeed_calledPartition;
		
		private System.Nullable<int> _outfeed_QOS_Callid;
		
		private System.Nullable<int> _outfeed_OQS_SequenceID;
		
		private string _outfeed_calledDeviceID;
		
		private string _outfeed_callingDeviceID;
		
		private System.Nullable<int> _outfeed_QOS_callLeg_id;
		
		private System.Nullable<System.DateTime> _outfeed_endDateTime;
		
		private System.Nullable<int> _outfeed_carrier_int;
		
		private string _outfeed_callername;
		
		private string _outfeed_departmentname;
		
		private string _outfeed_communityId;
		
		public tbl_outfeed()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_site_id_FK", DbType="Int NOT NULL")]
		public int outfeed_site_id_FK
		{
			get
			{
				return this._outfeed_site_id_FK;
			}
			set
			{
				if ((this._outfeed_site_id_FK != value))
				{
					this._outfeed_site_id_FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_versionnum", DbType="Char(1)")]
		public System.Nullable<char> outfeed_versionnum
		{
			get
			{
				return this._outfeed_versionnum;
			}
			set
			{
				if ((this._outfeed_versionnum != value))
				{
					this._outfeed_versionnum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_startdatetime", DbType="DateTime NOT NULL")]
		public System.DateTime outfeed_startdatetime
		{
			get
			{
				return this._outfeed_startdatetime;
			}
			set
			{
				if ((this._outfeed_startdatetime != value))
				{
					this._outfeed_startdatetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_pabxstartdatetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> outfeed_pabxstartdatetime
		{
			get
			{
				return this._outfeed_pabxstartdatetime;
			}
			set
			{
				if ((this._outfeed_pabxstartdatetime != value))
				{
					this._outfeed_pabxstartdatetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_extensionnumber", DbType="VarChar(100)")]
		public string outfeed_extensionnumber
		{
			get
			{
				return this._outfeed_extensionnumber;
			}
			set
			{
				if ((this._outfeed_extensionnumber != value))
				{
					this._outfeed_extensionnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_trunkaccesscode1", DbType="VarChar(6)")]
		public string outfeed_trunkaccesscode1
		{
			get
			{
				return this._outfeed_trunkaccesscode1;
			}
			set
			{
				if ((this._outfeed_trunkaccesscode1 != value))
				{
					this._outfeed_trunkaccesscode1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_trunkaccesscode2", DbType="VarChar(6)")]
		public string outfeed_trunkaccesscode2
		{
			get
			{
				return this._outfeed_trunkaccesscode2;
			}
			set
			{
				if ((this._outfeed_trunkaccesscode2 != value))
				{
					this._outfeed_trunkaccesscode2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_carrieraccesscode", DbType="VarChar(6)")]
		public string outfeed_carrieraccesscode
		{
			get
			{
				return this._outfeed_carrieraccesscode;
			}
			set
			{
				if ((this._outfeed_carrieraccesscode != value))
				{
					this._outfeed_carrieraccesscode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_dialleddigits", DbType="VarChar(35)")]
		public string outfeed_dialleddigits
		{
			get
			{
				return this._outfeed_dialleddigits;
			}
			set
			{
				if ((this._outfeed_dialleddigits != value))
				{
					this._outfeed_dialleddigits = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_accountcode", DbType="VarChar(6)")]
		public string outfeed_accountcode
		{
			get
			{
				return this._outfeed_accountcode;
			}
			set
			{
				if ((this._outfeed_accountcode != value))
				{
					this._outfeed_accountcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_routename", DbType="VarChar(255)")]
		public string outfeed_routename
		{
			get
			{
				return this._outfeed_routename;
			}
			set
			{
				if ((this._outfeed_routename != value))
				{
					this._outfeed_routename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_hohduration", DbType="Int")]
		public System.Nullable<int> outfeed_hohduration
		{
			get
			{
				return this._outfeed_hohduration;
			}
			set
			{
				if ((this._outfeed_hohduration != value))
				{
					this._outfeed_hohduration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_connectedduration", DbType="Int")]
		public System.Nullable<int> outfeed_connectedduration
		{
			get
			{
				return this._outfeed_connectedduration;
			}
			set
			{
				if ((this._outfeed_connectedduration != value))
				{
					this._outfeed_connectedduration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_calltype", DbType="VarChar(2)")]
		public string outfeed_calltype
		{
			get
			{
				return this._outfeed_calltype;
			}
			set
			{
				if ((this._outfeed_calltype != value))
				{
					this._outfeed_calltype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_destinationpointer", DbType="Int")]
		public System.Nullable<int> outfeed_destinationpointer
		{
			get
			{
				return this._outfeed_destinationpointer;
			}
			set
			{
				if ((this._outfeed_destinationpointer != value))
				{
					this._outfeed_destinationpointer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_codelength", DbType="Char(1)")]
		public System.Nullable<char> outfeed_codelength
		{
			get
			{
				return this._outfeed_codelength;
			}
			set
			{
				if ((this._outfeed_codelength != value))
				{
					this._outfeed_codelength = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_originatingtrunkgroup", DbType="VarChar(25)")]
		public string outfeed_originatingtrunkgroup
		{
			get
			{
				return this._outfeed_originatingtrunkgroup;
			}
			set
			{
				if ((this._outfeed_originatingtrunkgroup != value))
				{
					this._outfeed_originatingtrunkgroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_originatingtrunknumber", DbType="VarChar(25)")]
		public string outfeed_originatingtrunknumber
		{
			get
			{
				return this._outfeed_originatingtrunknumber;
			}
			set
			{
				if ((this._outfeed_originatingtrunknumber != value))
				{
					this._outfeed_originatingtrunknumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_outgoingtrunkgroup", DbType="VarChar(25)")]
		public string outfeed_outgoingtrunkgroup
		{
			get
			{
				return this._outfeed_outgoingtrunkgroup;
			}
			set
			{
				if ((this._outfeed_outgoingtrunkgroup != value))
				{
					this._outfeed_outgoingtrunkgroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_outgoingtrunknumber", DbType="VarChar(25)")]
		public string outfeed_outgoingtrunknumber
		{
			get
			{
				return this._outfeed_outgoingtrunknumber;
			}
			set
			{
				if ((this._outfeed_outgoingtrunknumber != value))
				{
					this._outfeed_outgoingtrunknumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_cost", DbType="Int")]
		public System.Nullable<int> outfeed_cost
		{
			get
			{
				return this._outfeed_cost;
			}
			set
			{
				if ((this._outfeed_cost != value))
				{
					this._outfeed_cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_alternatecost", DbType="Int")]
		public System.Nullable<int> outfeed_alternatecost
		{
			get
			{
				return this._outfeed_alternatecost;
			}
			set
			{
				if ((this._outfeed_alternatecost != value))
				{
					this._outfeed_alternatecost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_flags", DbType="Int")]
		public System.Nullable<int> outfeed_flags
		{
			get
			{
				return this._outfeed_flags;
			}
			set
			{
				if ((this._outfeed_flags != value))
				{
					this._outfeed_flags = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_installationid", DbType="VarChar(10)")]
		public string outfeed_installationid
		{
			get
			{
				return this._outfeed_installationid;
			}
			set
			{
				if ((this._outfeed_installationid != value))
				{
					this._outfeed_installationid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_contactid", DbType="VarChar(254)")]
		public string outfeed_contactid
		{
			get
			{
				return this._outfeed_contactid;
			}
			set
			{
				if ((this._outfeed_contactid != value))
				{
					this._outfeed_contactid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_padding", DbType="Char(1)")]
		public System.Nullable<char> outfeed_padding
		{
			get
			{
				return this._outfeed_padding;
			}
			set
			{
				if ((this._outfeed_padding != value))
				{
					this._outfeed_padding = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_allocationtype", DbType="Int")]
		public System.Nullable<int> outfeed_allocationtype
		{
			get
			{
				return this._outfeed_allocationtype;
			}
			set
			{
				if ((this._outfeed_allocationtype != value))
				{
					this._outfeed_allocationtype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_destinationtype_int", DbType="Int")]
		public System.Nullable<int> outfeed_destinationtype_int
		{
			get
			{
				return this._outfeed_destinationtype_int;
			}
			set
			{
				if ((this._outfeed_destinationtype_int != value))
				{
					this._outfeed_destinationtype_int = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_id_PK", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int outfeed_id_PK
		{
			get
			{
				return this._outfeed_id_PK;
			}
			set
			{
				if ((this._outfeed_id_PK != value))
				{
					this._outfeed_id_PK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_callingPartition", DbType="VarChar(200)")]
		public string outfeed_callingPartition
		{
			get
			{
				return this._outfeed_callingPartition;
			}
			set
			{
				if ((this._outfeed_callingPartition != value))
				{
					this._outfeed_callingPartition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_calledPartition", DbType="VarChar(200)")]
		public string outfeed_calledPartition
		{
			get
			{
				return this._outfeed_calledPartition;
			}
			set
			{
				if ((this._outfeed_calledPartition != value))
				{
					this._outfeed_calledPartition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_QOS_Callid", DbType="Int")]
		public System.Nullable<int> outfeed_QOS_Callid
		{
			get
			{
				return this._outfeed_QOS_Callid;
			}
			set
			{
				if ((this._outfeed_QOS_Callid != value))
				{
					this._outfeed_QOS_Callid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_OQS_SequenceID", DbType="Int")]
		public System.Nullable<int> outfeed_OQS_SequenceID
		{
			get
			{
				return this._outfeed_OQS_SequenceID;
			}
			set
			{
				if ((this._outfeed_OQS_SequenceID != value))
				{
					this._outfeed_OQS_SequenceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_calledDeviceID", DbType="VarChar(250)")]
		public string outfeed_calledDeviceID
		{
			get
			{
				return this._outfeed_calledDeviceID;
			}
			set
			{
				if ((this._outfeed_calledDeviceID != value))
				{
					this._outfeed_calledDeviceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_callingDeviceID", DbType="VarChar(250)")]
		public string outfeed_callingDeviceID
		{
			get
			{
				return this._outfeed_callingDeviceID;
			}
			set
			{
				if ((this._outfeed_callingDeviceID != value))
				{
					this._outfeed_callingDeviceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_QOS_callLeg_id", DbType="Int")]
		public System.Nullable<int> outfeed_QOS_callLeg_id
		{
			get
			{
				return this._outfeed_QOS_callLeg_id;
			}
			set
			{
				if ((this._outfeed_QOS_callLeg_id != value))
				{
					this._outfeed_QOS_callLeg_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_endDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> outfeed_endDateTime
		{
			get
			{
				return this._outfeed_endDateTime;
			}
			set
			{
				if ((this._outfeed_endDateTime != value))
				{
					this._outfeed_endDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_carrier_int", DbType="Int")]
		public System.Nullable<int> outfeed_carrier_int
		{
			get
			{
				return this._outfeed_carrier_int;
			}
			set
			{
				if ((this._outfeed_carrier_int != value))
				{
					this._outfeed_carrier_int = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_callername", DbType="VarChar(100)")]
		public string outfeed_callername
		{
			get
			{
				return this._outfeed_callername;
			}
			set
			{
				if ((this._outfeed_callername != value))
				{
					this._outfeed_callername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_departmentname", DbType="VarChar(100)")]
		public string outfeed_departmentname
		{
			get
			{
				return this._outfeed_departmentname;
			}
			set
			{
				if ((this._outfeed_departmentname != value))
				{
					this._outfeed_departmentname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outfeed_communityId", DbType="NVarChar(50)")]
		public string outfeed_communityId
		{
			get
			{
				return this._outfeed_communityId;
			}
			set
			{
				if ((this._outfeed_communityId != value))
				{
					this._outfeed_communityId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Directory")]
	public partial class Directory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _SiteId;
		
		private long _Extension;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSiteIdChanging(int value);
    partial void OnSiteIdChanged();
    partial void OnExtensionChanging(long value);
    partial void OnExtensionChanged();
    #endregion
		
		public Directory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteId", DbType="Int NOT NULL")]
		public int SiteId
		{
			get
			{
				return this._SiteId;
			}
			set
			{
				if ((this._SiteId != value))
				{
					this.OnSiteIdChanging(value);
					this.SendPropertyChanging();
					this._SiteId = value;
					this.SendPropertyChanged("SiteId");
					this.OnSiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="BigInt NOT NULL")]
		public long Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this.OnExtensionChanging(value);
					this.SendPropertyChanging();
					this._Extension = value;
					this.SendPropertyChanged("Extension");
					this.OnExtensionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_branding")]
	public partial class tbl_branding : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Email;
		
		private string _Username;
		
		private string _SiteName;
		
		private string _Url;
		
		private string _Colors;
		
		private string _Logo;
		
		private bool _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnColorsChanging(string value);
    partial void OnColorsChanged();
    partial void OnLogoChanging(string value);
    partial void OnLogoChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    #endregion
		
		public tbl_branding()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(100)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colors", DbType="VarChar(50)")]
		public string Colors
		{
			get
			{
				return this._Colors;
			}
			set
			{
				if ((this._Colors != value))
				{
					this.OnColorsChanging(value);
					this.SendPropertyChanging();
					this._Colors = value;
					this.SendPropertyChanged("Colors");
					this.OnColorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="VarChar(MAX)")]
		public string Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this.OnLogoChanging(value);
					this.SendPropertyChanging();
					this._Logo = value;
					this.SendPropertyChanged("Logo");
					this.OnLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_email")]
	public partial class tbl_email : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Email;
		
		private string _Username;
		
		private string _Password;
		
		private string _Host;
		
		private System.Nullable<int> _Port;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnHostChanging(string value);
    partial void OnHostChanged();
    partial void OnPortChanging(System.Nullable<int> value);
    partial void OnPortChanged();
    #endregion
		
		public tbl_email()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(MAX)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(MAX)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Host", DbType="VarChar(MAX)")]
		public string Host
		{
			get
			{
				return this._Host;
			}
			set
			{
				if ((this._Host != value))
				{
					this.OnHostChanging(value);
					this.SendPropertyChanging();
					this._Host = value;
					this.SendPropertyChanged("Host");
					this.OnHostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Port", DbType="Int")]
		public System.Nullable<int> Port
		{
			get
			{
				return this._Port;
			}
			set
			{
				if ((this._Port != value))
				{
					this.OnPortChanging(value);
					this.SendPropertyChanging();
					this._Port = value;
					this.SendPropertyChanged("Port");
					this.OnPortChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
