#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVProcessor.Database.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Centile_dev")]
	public partial class CentileDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_company(tbl_company instance);
    partial void Updatetbl_company(tbl_company instance);
    partial void Deletetbl_company(tbl_company instance);
    partial void Inserttbl_site(tbl_site instance);
    partial void Updatetbl_site(tbl_site instance);
    partial void Deletetbl_site(tbl_site instance);
    #endregion
		
		public CentileDataContext() : 
				base(global::CSVProcessor.Database.Properties.Settings.Default.Centile_devConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CentileDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CentileDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CentileDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CentileDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_company> tbl_companies
		{
			get
			{
				return this.GetTable<tbl_company>();
			}
		}
		
		public System.Data.Linq.Table<tbl_site> tbl_sites
		{
			get
			{
				return this.GetTable<tbl_site>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_company")]
	public partial class tbl_company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _company_id_PK;
		
		private string _company_name;
		
		private System.Nullable<int> _address_id_PK;
		
		private System.Nullable<int> _branding_id;
		
		private System.Nullable<int> _tbl_company_level_id_PK;
		
		private string _tbl_Centile_Community_id_FK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncompany_id_PKChanging(int value);
    partial void Oncompany_id_PKChanged();
    partial void Oncompany_nameChanging(string value);
    partial void Oncompany_nameChanged();
    partial void Onaddress_id_PKChanging(System.Nullable<int> value);
    partial void Onaddress_id_PKChanged();
    partial void Onbranding_idChanging(System.Nullable<int> value);
    partial void Onbranding_idChanged();
    partial void Ontbl_company_level_id_PKChanging(System.Nullable<int> value);
    partial void Ontbl_company_level_id_PKChanged();
    partial void Ontbl_Centile_Community_id_FKChanging(string value);
    partial void Ontbl_Centile_Community_id_FKChanged();
    #endregion
		
		public tbl_company()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_id_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int company_id_PK
		{
			get
			{
				return this._company_id_PK;
			}
			set
			{
				if ((this._company_id_PK != value))
				{
					this.Oncompany_id_PKChanging(value);
					this.SendPropertyChanging();
					this._company_id_PK = value;
					this.SendPropertyChanged("company_id_PK");
					this.Oncompany_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="VarChar(50)")]
		public string company_name
		{
			get
			{
				return this._company_name;
			}
			set
			{
				if ((this._company_name != value))
				{
					this.Oncompany_nameChanging(value);
					this.SendPropertyChanging();
					this._company_name = value;
					this.SendPropertyChanged("company_name");
					this.Oncompany_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_id_PK", DbType="Int")]
		public System.Nullable<int> address_id_PK
		{
			get
			{
				return this._address_id_PK;
			}
			set
			{
				if ((this._address_id_PK != value))
				{
					this.Onaddress_id_PKChanging(value);
					this.SendPropertyChanging();
					this._address_id_PK = value;
					this.SendPropertyChanged("address_id_PK");
					this.Onaddress_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branding_id", DbType="Int")]
		public System.Nullable<int> branding_id
		{
			get
			{
				return this._branding_id;
			}
			set
			{
				if ((this._branding_id != value))
				{
					this.Onbranding_idChanging(value);
					this.SendPropertyChanging();
					this._branding_id = value;
					this.SendPropertyChanged("branding_id");
					this.Onbranding_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_company_level_id_PK", DbType="Int")]
		public System.Nullable<int> tbl_company_level_id_PK
		{
			get
			{
				return this._tbl_company_level_id_PK;
			}
			set
			{
				if ((this._tbl_company_level_id_PK != value))
				{
					this.Ontbl_company_level_id_PKChanging(value);
					this.SendPropertyChanging();
					this._tbl_company_level_id_PK = value;
					this.SendPropertyChanged("tbl_company_level_id_PK");
					this.Ontbl_company_level_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Centile_Community_id_FK", DbType="VarChar(150)")]
		public string tbl_Centile_Community_id_FK
		{
			get
			{
				return this._tbl_Centile_Community_id_FK;
			}
			set
			{
				if ((this._tbl_Centile_Community_id_FK != value))
				{
					this.Ontbl_Centile_Community_id_FKChanging(value);
					this.SendPropertyChanging();
					this._tbl_Centile_Community_id_FK = value;
					this.SendPropertyChanged("tbl_Centile_Community_id_FK");
					this.Ontbl_Centile_Community_id_FKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_site")]
	public partial class tbl_site : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _site_id_PK;
		
		private System.Nullable<int> _site_number;
		
		private string _site_name;
		
		private string _site_type;
		
		private System.Nullable<int> _site_userlimit;
		
		private System.Nullable<System.DateTime> _site_lastinfeedmodifieddate;
		
		private string _site_lastinfeeddirectory;
		
		private System.Nullable<long> _site_lastinfeedreadrow;
		
		private System.Nullable<System.DateTime> _site_lastoutfeedmodifieddate;
		
		private string _site_lastoutfeeddirectory;
		
		private System.Nullable<long> _site_lastoutfeedreadrow;
		
		private System.Nullable<int> _company_id_PK;
		
		private System.Nullable<int> _address_id_PK;
		
		private System.Nullable<int> _site_datadropfrequency;
		
		private System.Nullable<bool> _Site_termsandconditions;
		
		private System.Nullable<bool> _Site_LyncSwitch;
		
		private string _Site_SwitchName;
		
		private string _Site_LyncDomain;
		
		private string _tbl_Centile_Community_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsite_id_PKChanging(int value);
    partial void Onsite_id_PKChanged();
    partial void Onsite_numberChanging(System.Nullable<int> value);
    partial void Onsite_numberChanged();
    partial void Onsite_nameChanging(string value);
    partial void Onsite_nameChanged();
    partial void Onsite_typeChanging(string value);
    partial void Onsite_typeChanged();
    partial void Onsite_userlimitChanging(System.Nullable<int> value);
    partial void Onsite_userlimitChanged();
    partial void Onsite_lastinfeedmodifieddateChanging(System.Nullable<System.DateTime> value);
    partial void Onsite_lastinfeedmodifieddateChanged();
    partial void Onsite_lastinfeeddirectoryChanging(string value);
    partial void Onsite_lastinfeeddirectoryChanged();
    partial void Onsite_lastinfeedreadrowChanging(System.Nullable<long> value);
    partial void Onsite_lastinfeedreadrowChanged();
    partial void Onsite_lastoutfeedmodifieddateChanging(System.Nullable<System.DateTime> value);
    partial void Onsite_lastoutfeedmodifieddateChanged();
    partial void Onsite_lastoutfeeddirectoryChanging(string value);
    partial void Onsite_lastoutfeeddirectoryChanged();
    partial void Onsite_lastoutfeedreadrowChanging(System.Nullable<long> value);
    partial void Onsite_lastoutfeedreadrowChanged();
    partial void Oncompany_id_PKChanging(System.Nullable<int> value);
    partial void Oncompany_id_PKChanged();
    partial void Onaddress_id_PKChanging(System.Nullable<int> value);
    partial void Onaddress_id_PKChanged();
    partial void Onsite_datadropfrequencyChanging(System.Nullable<int> value);
    partial void Onsite_datadropfrequencyChanged();
    partial void OnSite_termsandconditionsChanging(System.Nullable<bool> value);
    partial void OnSite_termsandconditionsChanged();
    partial void OnSite_LyncSwitchChanging(System.Nullable<bool> value);
    partial void OnSite_LyncSwitchChanged();
    partial void OnSite_SwitchNameChanging(string value);
    partial void OnSite_SwitchNameChanged();
    partial void OnSite_LyncDomainChanging(string value);
    partial void OnSite_LyncDomainChanged();
    partial void Ontbl_Centile_Community_IdChanging(string value);
    partial void Ontbl_Centile_Community_IdChanged();
    #endregion
		
		public tbl_site()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_id_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int site_id_PK
		{
			get
			{
				return this._site_id_PK;
			}
			set
			{
				if ((this._site_id_PK != value))
				{
					this.Onsite_id_PKChanging(value);
					this.SendPropertyChanging();
					this._site_id_PK = value;
					this.SendPropertyChanged("site_id_PK");
					this.Onsite_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_number", DbType="Int")]
		public System.Nullable<int> site_number
		{
			get
			{
				return this._site_number;
			}
			set
			{
				if ((this._site_number != value))
				{
					this.Onsite_numberChanging(value);
					this.SendPropertyChanging();
					this._site_number = value;
					this.SendPropertyChanged("site_number");
					this.Onsite_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_name", DbType="VarChar(250)")]
		public string site_name
		{
			get
			{
				return this._site_name;
			}
			set
			{
				if ((this._site_name != value))
				{
					this.Onsite_nameChanging(value);
					this.SendPropertyChanging();
					this._site_name = value;
					this.SendPropertyChanged("site_name");
					this.Onsite_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_type", DbType="NVarChar(50)")]
		public string site_type
		{
			get
			{
				return this._site_type;
			}
			set
			{
				if ((this._site_type != value))
				{
					this.Onsite_typeChanging(value);
					this.SendPropertyChanging();
					this._site_type = value;
					this.SendPropertyChanged("site_type");
					this.Onsite_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_userlimit", DbType="Int")]
		public System.Nullable<int> site_userlimit
		{
			get
			{
				return this._site_userlimit;
			}
			set
			{
				if ((this._site_userlimit != value))
				{
					this.Onsite_userlimitChanging(value);
					this.SendPropertyChanging();
					this._site_userlimit = value;
					this.SendPropertyChanged("site_userlimit");
					this.Onsite_userlimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastinfeedmodifieddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> site_lastinfeedmodifieddate
		{
			get
			{
				return this._site_lastinfeedmodifieddate;
			}
			set
			{
				if ((this._site_lastinfeedmodifieddate != value))
				{
					this.Onsite_lastinfeedmodifieddateChanging(value);
					this.SendPropertyChanging();
					this._site_lastinfeedmodifieddate = value;
					this.SendPropertyChanged("site_lastinfeedmodifieddate");
					this.Onsite_lastinfeedmodifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastinfeeddirectory", DbType="VarChar(100)")]
		public string site_lastinfeeddirectory
		{
			get
			{
				return this._site_lastinfeeddirectory;
			}
			set
			{
				if ((this._site_lastinfeeddirectory != value))
				{
					this.Onsite_lastinfeeddirectoryChanging(value);
					this.SendPropertyChanging();
					this._site_lastinfeeddirectory = value;
					this.SendPropertyChanged("site_lastinfeeddirectory");
					this.Onsite_lastinfeeddirectoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastinfeedreadrow", DbType="BigInt")]
		public System.Nullable<long> site_lastinfeedreadrow
		{
			get
			{
				return this._site_lastinfeedreadrow;
			}
			set
			{
				if ((this._site_lastinfeedreadrow != value))
				{
					this.Onsite_lastinfeedreadrowChanging(value);
					this.SendPropertyChanging();
					this._site_lastinfeedreadrow = value;
					this.SendPropertyChanged("site_lastinfeedreadrow");
					this.Onsite_lastinfeedreadrowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastoutfeedmodifieddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> site_lastoutfeedmodifieddate
		{
			get
			{
				return this._site_lastoutfeedmodifieddate;
			}
			set
			{
				if ((this._site_lastoutfeedmodifieddate != value))
				{
					this.Onsite_lastoutfeedmodifieddateChanging(value);
					this.SendPropertyChanging();
					this._site_lastoutfeedmodifieddate = value;
					this.SendPropertyChanged("site_lastoutfeedmodifieddate");
					this.Onsite_lastoutfeedmodifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastoutfeeddirectory", DbType="VarChar(100)")]
		public string site_lastoutfeeddirectory
		{
			get
			{
				return this._site_lastoutfeeddirectory;
			}
			set
			{
				if ((this._site_lastoutfeeddirectory != value))
				{
					this.Onsite_lastoutfeeddirectoryChanging(value);
					this.SendPropertyChanging();
					this._site_lastoutfeeddirectory = value;
					this.SendPropertyChanged("site_lastoutfeeddirectory");
					this.Onsite_lastoutfeeddirectoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_lastoutfeedreadrow", DbType="BigInt")]
		public System.Nullable<long> site_lastoutfeedreadrow
		{
			get
			{
				return this._site_lastoutfeedreadrow;
			}
			set
			{
				if ((this._site_lastoutfeedreadrow != value))
				{
					this.Onsite_lastoutfeedreadrowChanging(value);
					this.SendPropertyChanging();
					this._site_lastoutfeedreadrow = value;
					this.SendPropertyChanged("site_lastoutfeedreadrow");
					this.Onsite_lastoutfeedreadrowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_id_PK", DbType="Int")]
		public System.Nullable<int> company_id_PK
		{
			get
			{
				return this._company_id_PK;
			}
			set
			{
				if ((this._company_id_PK != value))
				{
					this.Oncompany_id_PKChanging(value);
					this.SendPropertyChanging();
					this._company_id_PK = value;
					this.SendPropertyChanged("company_id_PK");
					this.Oncompany_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_id_PK", DbType="Int")]
		public System.Nullable<int> address_id_PK
		{
			get
			{
				return this._address_id_PK;
			}
			set
			{
				if ((this._address_id_PK != value))
				{
					this.Onaddress_id_PKChanging(value);
					this.SendPropertyChanging();
					this._address_id_PK = value;
					this.SendPropertyChanged("address_id_PK");
					this.Onaddress_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_datadropfrequency", DbType="Int")]
		public System.Nullable<int> site_datadropfrequency
		{
			get
			{
				return this._site_datadropfrequency;
			}
			set
			{
				if ((this._site_datadropfrequency != value))
				{
					this.Onsite_datadropfrequencyChanging(value);
					this.SendPropertyChanging();
					this._site_datadropfrequency = value;
					this.SendPropertyChanged("site_datadropfrequency");
					this.Onsite_datadropfrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_termsandconditions", DbType="Bit")]
		public System.Nullable<bool> Site_termsandconditions
		{
			get
			{
				return this._Site_termsandconditions;
			}
			set
			{
				if ((this._Site_termsandconditions != value))
				{
					this.OnSite_termsandconditionsChanging(value);
					this.SendPropertyChanging();
					this._Site_termsandconditions = value;
					this.SendPropertyChanged("Site_termsandconditions");
					this.OnSite_termsandconditionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_LyncSwitch", DbType="Bit")]
		public System.Nullable<bool> Site_LyncSwitch
		{
			get
			{
				return this._Site_LyncSwitch;
			}
			set
			{
				if ((this._Site_LyncSwitch != value))
				{
					this.OnSite_LyncSwitchChanging(value);
					this.SendPropertyChanging();
					this._Site_LyncSwitch = value;
					this.SendPropertyChanged("Site_LyncSwitch");
					this.OnSite_LyncSwitchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_SwitchName", DbType="VarChar(50)")]
		public string Site_SwitchName
		{
			get
			{
				return this._Site_SwitchName;
			}
			set
			{
				if ((this._Site_SwitchName != value))
				{
					this.OnSite_SwitchNameChanging(value);
					this.SendPropertyChanging();
					this._Site_SwitchName = value;
					this.SendPropertyChanged("Site_SwitchName");
					this.OnSite_SwitchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_LyncDomain", DbType="VarChar(50)")]
		public string Site_LyncDomain
		{
			get
			{
				return this._Site_LyncDomain;
			}
			set
			{
				if ((this._Site_LyncDomain != value))
				{
					this.OnSite_LyncDomainChanging(value);
					this.SendPropertyChanging();
					this._Site_LyncDomain = value;
					this.SendPropertyChanged("Site_LyncDomain");
					this.OnSite_LyncDomainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_Centile_Community_Id", DbType="VarChar(150)")]
		public string tbl_Centile_Community_Id
		{
			get
			{
				return this._tbl_Centile_Community_Id;
			}
			set
			{
				if ((this._tbl_Centile_Community_Id != value))
				{
					this.Ontbl_Centile_Community_IdChanging(value);
					this.SendPropertyChanging();
					this._tbl_Centile_Community_Id = value;
					this.SendPropertyChanged("tbl_Centile_Community_Id");
					this.Ontbl_Centile_Community_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
